version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROD_DB_HOST=${PROD_DB_HOST}
      - PROD_DB_PORT=${PROD_DB_PORT}
      - PROD_DB_NAME=${PROD_DB_NAME}
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - PROD_BOT_NAME=${PROD_BOT_NAME}
      - PROD_BOT_TOKEN=${PROD_BOT_TOKEN}
    ports:
      - "80:8080"
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=snwm1337
    volumes:
      - dbdata:/var/lib/postgresql/data
      # - ./src/main/resources/sql:/docker-entrypoint-initdb.d
volumes:
  dbdata:
