spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: Postgres

  sql:
    init:
      mode: always

  bot:
    username: ${PROD_BOT_NAME}
    token: ${PROD_BOT_TOKEN}

  jpa:
    hibernate:
      ddl-auto: update