spring:
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: Postgres

  sql:
    init:
      mode: always

  bot:
    username: ${PROD_BOT_NAME}
    token: ${PROD_BOT_TOKEN}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

# server:
#   ssl:
#     key-store: classpath:keystore.p12
#     key-store-password: snwm1337
#     key-store-type: PKCS12
#     key-alias: myalias
#   port: 8443
      