spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wordbot
    username: postgres
    password: admin
    name: Postgres

  sql:
    init:
      mode: always

  bot:
    username: ${PROD_BOT_NAME}
    token: ${PROD_BOT_TOKEN}

  jpa:
    hibernate:
      ddl-auto: update

      