

SELECT w.* FROM user_words uw JOIN words w ON uw.word_id = w.id WHERE uw.user_id = 589460486 ORDER BY RANDOM() LIMIT 1;

CREATE INDEX idx_user_id ON user_words (user_id);

SELECT CONCAT(ROUND(SUM(correct_attempts) / (SUM(correct_attempts) + SUM(incorrect_attempts)) * 100), '%') AS success_rate FROM user_word_stats WHERE user_id = 589460486

SELECT
    SUM(correct_attempts) AS total_correct_attempts,
    SUM(correct_attempts + incorrect_attempts) AS total_attempts
FROM
    user_word_stats
WHERE
    user_id = 589460486;

    SELECT SUM(correct_attempts) AS total_correct_attempts, SUM(correct_attempts + incorrect_attempts) AS total_attempts FROM user_word_stats WHERE user_id = 589460486;

INSERT INTO words (word, translation, transcription)
VALUES
    ('to be', 'Быть', '[tə biː]'),
    ('to do', 'Делать', '[du]'),
    ('to feel', 'Чувствовать', '[fiːl]'),
    ('to see', 'Видеть', '[siː]'),
    ('to hear', 'Слышать', '[hɪər]'),
    ('to run', 'Бежать', '[rʌn]'),
    ('to get', 'Получать', '[ɡet]'),
    ('to make', 'Сделать', '[meɪk]'),
    ('to cook', 'Готовить', '[kʊk]'),
    ('to sing', 'Петь', '[sɪŋ]'),
    ('to speak', 'Разговаривать', '[spiːk]'),
    ('to say', 'Говорить', '[seɪ]'),
    ('to tell', 'Рассказывать', '[tel]'),
    ('to take', 'Брать', '[teɪk]'),
    ('to sit', 'Садиться', '[sɪt]'),
    ('to stand', 'Стоять', '[stænd]'),
    ('to laugh', 'Смеяться', '[lɑːf]'),
    ('to smile', 'Улыбаться', '[smaɪl]'),
    ('to open', 'Открывать', '[ˈəʊpən]'),
    ('to close', 'Закрывать', '[kləʊz]'),
    ('to love', 'Любить', '[lʌv]'),
    ('to like', 'Нравиться', '[laɪk]'),
    ('to give', 'Давать', '[ɡɪv]'),
    ('to bring', 'Приносить', '[brɪŋ]'),
    ('to breath', 'Дышать', '[breθ]'),
    ('to buy', 'Покупать', '[baɪ]'),
    ('to sell', 'Продавать', '[sel]'),
    ('to forget', 'Забывать', '[fəˈɡet]'),
    ('to believe', 'Верить', '[bɪˈliːv]'),
    ('to have', 'Иметь', '[həv]'),
    ('to go', 'Идти', '[ɡəʊ]'),
    ('to know', 'Знать', '[nəʊ]'),
    ('to think', 'Думать', '[θɪŋk]'),
    ('to come', 'Приходить', '[kʌm]'),
    ('to want', 'Хотеть', '[wɒnt]'),
    ('to use', 'Использовать', '[juːz]'),
    ('to find', 'Находить', '[faɪnd]'),
    ('to work', 'Работать', '[wɜːk]'),
    ('to eat', 'Есть', '[iːt]'),
    ('to drink', 'Пить', '[drɪŋk]'),
    ('to write', 'Писать', '[raɪt]'),
    ('to read', 'Читать', '[riːd]'),
    ('to call', 'Звонить', '[kɔːl]'),
    ('to try', 'Пытаться', '[traɪ]'),
    ('to need', 'Нуждаться', '[niːd]'),
    ('to become', 'Становиться', '[bɪˈkʌm]'),
    ('to put', 'Класть', '[pʊt]'),
    ('to leave', 'Оставлять', '[liːv]'),
    ('to pay', 'Платить', '[peɪ]'),
    ('to play', 'Играть', '[pleɪ]'),
    ('to pray', 'Молиться', '[preɪ]'),
    ('to stay', 'Оставаться', '[steɪ]'),
    ('to mean', 'Означать', '[miːn]'),
    ('to keep', 'Держать, хранить', '[kiːp]'),
    ('to let', 'Оставлять', '[let]'),
    ('to begin', 'Начинать', '[bɪˈɡɪn]'),
    ('to start', 'Стартовать', '[stɑːt]'),
    ('to finish', 'Заканчивать', '[ˈfɪnɪʃ]'),
    ('to help', 'Помогать', '[help]'),
    ('to show', 'Показывать', '[ʃəʊ]'),
    ('to cry', 'Плакать', '[kraɪ]'),
    ('to move', 'Двигаться', '[muːv]'),
    ('to jump', 'Прыгать', '[dʒʌmp]'),
    ('to live', 'Жить', '[lɪv]'),
    ('to die', 'Умирать', '[daɪ]'),
    ('to happen', 'Случаться', '[ˈhæpən]'),
    ('to lose', 'Проигрывать', '[luːz]'),
    ('to hate', 'Ненавидеть', '[heɪt]'),
    ('to include', 'Включать в себя', '[ɪnˈkluːd]'),
    ('to turn on', 'Включать (о приборе)', '[tɜːn ɒn]'),
    ('to turn off', 'Выключать', '[tɜːn ɒf]'),
    ('to continue', 'Продолжать', '[kənˈtɪnjuː]'),
    ('to change', 'Менять', '[tʃeɪndʒ]'),
    ('to wash', 'Мыть', '[wɒʃ]'),
    ('to clean', 'Убирать, очищать', '[kliːn]'),
    ('to lead', 'Вести', '[liːd]'),
    ('to understand', 'Понимать', '[ˌʌndəˈstænd]'),
    ('to watch', 'Смотреть', '[wɒtʃ]'),
    ('to discover', 'Исследовать', '[dɪˈskʌvə(r)]'),
    ('To imagine', 'Представлять', '[ɪˈmædʒɪn]'),
    ('To introduce', 'Представить', '[ˌɪntrəˈdjuːs]'),
    ('To follow', 'Следовать', '[ˈfɒləʊ]'),
    ('To create', 'Создавать', '[kriˈeɪt]'),
    ('To grow', 'Расти', '[ɡrəʊ]'),
    ('To spend', 'Тратить', '[spend]'),
    ('To win', 'Выигрывать', '[wɪn]'),
    ('To offer', 'Предлагать', '[ˈɒfə(r)]'),
    ('To learn', 'Изучать', '[lɜːn]'),
    ('To appear', 'Появляться', '[əˈpɪə(r)]'),
    ('To disappear', 'Исчезать', '[ˌdɪsəˈpɪə(r)]'),
    ('To build', 'Строить', '[bɪld]'),
    ('To break', 'Ломать', '[breɪk]'),
    ('To send', 'Посылать', '[send]'),
    ('To fall', 'Падать', '[fɔːl]'),
    ('To cut', 'Резать', '[kʌt]'),
    ('To achieve', 'Достигать', '[əˈtʃiːv]'),
    ('To communicate', 'Общаться', '[kəˈmjuːnɪkeɪt]'),
    ('To kill', 'Убивать', '[kɪl]'),
    ('To pass', 'Проходить', '[pɑːs]'),
    ('To fly', 'Летать', '[flaɪ]'),
    ('To swim', 'Плавать', '[swɪm]'),
    ('To decide', 'Решать', '[dɪˈsaɪd]'),
    ('To return', 'Возвращаться', '[rɪˈtɜːn]'),
    ('To hope', 'Надеяться', '[həʊp]'),
    ('To explain', 'Объяснять', '[ɪkˈspleɪn]'),
    ('To propose', 'Предлагать', '[prəˈpəʊz]'),
    ('To develop', 'Развивать', '[dɪˈveləp]'),
    ('To support', 'Поддерживать', '[səˈpɔːt]'),
    ('To dance', 'Танцевать', '[dɑːns]'),
    ('To draw', 'Рисовать', '[drɔː]'),
    ('To book', 'Бронировать', '[bʊk]'),
    ('To be afraid', 'Бояться', '[bi əˈfreɪd]'),
    ('To agree', 'Соглашаться', '[əˈɡriː]'),
    ('To check up', 'Проверять', '[tʃek ʌp]'),
    ('To delete', 'Удалять', '[dɪˈliːt]'),
    ('To choose', 'Выбирать', '[tʃuːz]'),
    ('To catch', 'Ловить', '[kætʃ]'),
    ('To ask', 'Спрашивать', '[ɑːsk]'),
    ('To answer', 'Отвечать', '[ˈɑːnsə(r)]'),
    ('To hesitate', 'Сомневаться', '[ˈhezɪteɪt]'),
    ('air', 'Воздух', '[ən eə(r)]'),
    ('wind', 'Ветер', '[wɪnd]'),
    ('water', 'Вода', '[ˈwɔːtə(r)]'),
    ('west', 'Запад', '[west]'),
    ('east', 'Восток', '[iːst]'),
    ('north', 'Север', '[nɔːθ]'),
    ('south', 'Юг', '[saʊθ]'),
    ('tree', 'Дерево', '[triː]'),
    ('sea', 'Море', '[siː]'),
    ('ocean', 'Океан', '[ˈəʊʃn]'),
    ('rock', 'Скала', '[rɒk]'),
    ('plant', 'Растение', '[plɑːnt]'),
    ('flower', 'Цветок', '[ˈflaʊə(r)]'),
    ('forest', 'Лес', '[ˈfɒrɪst]'),
    ('person', 'Личность', '[ˈpɜːsn]'),
    ('night', 'Ночь', '[naɪt]'),
    ('morning', 'Утро', '[ˈmɔːnɪŋ]'),
    ('day', 'День', '[deɪ]'),
    ('evening', 'Вечер', '[ˈiːvnɪŋ]'),
    ('life', 'Жизнь', '[laɪf]'),
    ('mountain', 'Гора', '[ˈmaʊntən]'),
    ('land', 'Земля', '[lænd]'),
    ('house', 'Дом', '[haʊs]'),
    ('fire', 'Огонь', '[ˈfaɪə(r)]'),
    ('country', 'Страна', '[ˈkʌntri]'),
    ('animal', 'Животное', '[ˈænɪml]'),
    ('bird', 'Птица', '[bɜːd]'),
    ('fish', 'Рыба', '[fɪʃ]'),
    ('insect', 'Насекомое', '[ˈɪnsekt]'),
    ('city', 'Город', '[ˈsɪti]'),
    ('world', 'Мир', '[wɜːld]'),
    ('boy', 'Мальчик', '[bɔɪ]'),
  ('girl', 'Девочка', '[ɡɜːl]'),
  ('mother', 'Мама', '[ˈmʌðə(r)]'),
  ('father', 'Отец', '[ˈfɑːðə(r)]'),
  ('son', 'Сын', '[sʌn]'),
  ('daughter', 'Дочь', '[ˈdɔːtə(r)]'),
  ('baby', 'Малыш', '[ˈbeɪbi]'),
  ('family', 'Семья', '[ˈfæməli]'),
  ('grand mother', 'Бабушка', '[ɡrænd ˈməT͟Hər]'),
  ('grand father', 'Дедушка', '[ɡrænd ˈfɑːðə(r)]'),
  ('children', 'Дети', '[ˈtʃɪl.drən]'),
  ('home', 'Дом', '[həʊm]'),
  ('love', 'Любовь', '[lʌv]'),
  ('apartment', 'Квартира', '[əˈpɑːtmənt]'),
  ('joy', 'Радость', '[dʒɔɪ]'),
  ('nephew', 'Племянник', '[ˈnefjuː]'),
  ('aunt', 'Тетя', '[ɑːnt]'),
  ('uncle', 'Дядя', '[ˈʌŋkl]'),
  ('cousin', 'Двоюродная сестра/брат', '[ˈkʌzn]'),
  ('man', 'Мужчина', '[mæn]'),
  ('woman', 'Женщина', '[ˈwʊmən]'),
  ('child', 'Ребенок', '[tʃaɪld]'),
  ('sister', 'Сестра', '[ˈsɪstə(r)]'),
  ('brother', 'Брат', '[ˈbrʌðə(r)]'),
  ('Relatives', 'Родственники', '[ˈrel.ə.tɪv]'),
  ('friend', 'Друг', '[frend]'),
  ('wife', 'Жена', '[waɪf]'),
  ('husband', 'Муж', '[ˈhʌzbənd]'),
  ('address', 'Адрес', '[əˈdres]'),
  ('happiness', 'Счастье', '[ˈhæp.i.nəs]'),
  ('People', 'Люди', '[ˈpiːpl]'),
  ('phone', 'Телефон', '[fəʊn]'),
  ('question', 'Вопрос', '[ˈkwestʃən]'),
  ('place', 'Место', '[pleɪs]'),
  ('market', 'Рынок', '[ˈmɑːkɪt]'),
  ('order', 'Заказ', '[ˈɔːdə(r)]'),
  ('food', 'Еда', '[fuːd]'),
  ('work', 'Работа', '[wɜːk]'),
  ('communication', 'Общение', '[kəˌmjuːnɪˈkeɪʃn]'),
  ('story', 'История', '[ˈstɔːri]'),
  ('relax', 'Отдых', '[rɪˈlæks]'),
  ('time', 'Время', '[taɪm]'),
  ('word', 'Слово', '[wɜːd]'),
  ('dialogue', 'Диалог', '[ˈdaɪ.ə.lɒɡ]'),
  ('meeting', 'Встреча', '[ˈmiːtɪŋ]'),
  ('week', 'Неделя', '[wiːk]'),
  ('distance', 'Дистанция', '[ˈdɪstəns]'),
  ('club', 'Клуб', '[klʌb]'),
  ('theatre', 'Театр', '[ˈθɪətə(r)]'),
  ('cinema', 'Кинотеатр', '[ˈsɪnəmə]'),
  ('coffee shop', 'Кофейня', '[ˈkɒfi ʃɒp]'),
  ('friendship', 'Дружба', '[ˈfrendʃɪp]'),
  ('behavior', 'Поведение', '[bɪˈheɪ.vjər]'),
  ('attitude', 'Отношение', '[ˈætɪtjuːd]'),
  ('student', 'Студент', '[ˈstjuːdnt]'),
  ('university', 'Университет', '[ˌjuːnɪˈvɜːsəti]'),
  ('union', 'Объединение', '[ˈjuːniən]'),
  ('party', 'Вечеринка', '[ˈpɑːti]'),
  ('date', 'Свидание', '[deɪt]'),
  ('sweetheart', 'Партнер, возлюбленный', '[ˈswiːt.hɑːt]'),
  ('leisure time', 'Досуг', '[ˈleʒ.ər taɪm]'),
  ('road', 'Дорога', '[rəʊd]'),
  ('ticket', 'Билет', '[ˈtɪkɪt]'),
  ('map', 'Карта', '[mæp]'),
  ('motel', 'Мотель', '[məʊˈtel]'),
  ('highway', 'Шоссе', '[ˈhaɪweɪ]'),
  ('reception', 'Регистратура, ресепшн', '[rɪˈsepʃn]'),
  ('wallet', 'Бумажник', '[ˈwɒlɪt]'),
  ('bank', 'Банк', '[bæŋk]'),
  ('subway', 'Метро', '[ˈsʌb.weɪ]'),
  ('cab', 'Такси', '[kæb]'),
  ('parking', 'Парковка', '[ˈpɑː.kɪŋ]'),
  ('food order', 'Заказ еды', '[fuːd ˈɔːdə(r)]'),
  ('cash', 'Наличные', '[kæʃ]'),
  ('passport', 'Паспорт', '[ˈpɑːspɔːt]'),
  ('permission', 'Разрешение', '[pəˈmɪʃn]'),
  ('lawyer', 'Адвокат', '[ˈlɔːjə(r)]'),
  ('problem', 'Проблема', '[ˈprɒbləm]'),
  ('waiting room', 'Зал ожидания', '[weɪtin: ruːm]'),
  ('transfer', 'Пересадка', '[trænsˈfɜː(r)]'),
  ('bag', 'Сумка', '[bæɡ]'),
  ('suitcase', 'Чемодан', '[ˈsuːtkeɪs]'),
  ('property', 'Имущество', '[ˈprɒpəti]'),
  ('law', 'Право, закон', '[lɔː]'),
  ('police station', 'Полицейский участок', '[pəˈliːs ˈsteɪʃn]'),
  ('price', 'Стоимость, цена', '[praɪs]'),
  ('price list', 'Ценник', '[praɪs lɪst]'),
  ('courier', 'Курьер', '[ˈkʊr.i.ər]'),
  ('delivery', 'Доставка', '[dɪˈlɪvəri]'),
  ('location', 'Местоположение', '[ləʊˈkeɪʃn]'),
  ('route', 'Маршрут', '[ruːt]'),
  ('agreement', 'Договор', '[əˈɡriːmənt]'),
  ('hospital', 'Больница', '[ˈhɒspɪtl]'),
  ('ambulance', 'Скорая помощь', '[ˈæmbjələns]'),
  ('cash', 'Наличные', '[kæʃ]'),
  ('passport', 'Паспорт', '[ˈpɑːspɔːt]'),
  ('permission', 'Разрешение', '[pəˈmɪʃn]'),
  ('afraid', 'Напуганный', '[əˈfreɪd]'),
  ('angry', 'Сердитый', '[ˈæŋɡri]'),
  ('asleep', 'Спящий', '[əˈsliːp]'),
  ('attentive', 'Внимательный', '[əˈten.tɪv]'),
  ('available', 'Доступный', '[əˈveɪləbl]'),
  ('basic', 'Базовый', '[ˈbeɪsɪk]'),
  ('beautiful', 'Красивый', '[ˈbjuːtɪfl]'),
  ('big', 'Большой', '[bɪɡ]'),
  ('brave', 'Смелый', '[breɪv]'),
  ('busy', 'Занятой', '[ˈbɪzi]'),
  ('calm', 'Спокойный', '[kɑːm]'),
  ('careful', 'Внимательный, заботливый', '[ˈkeəfl]'),
  ('cheap', 'Дешевый', '[tʃiːp]'),
  ('clean', 'Чистый', '[kliːn]'),
  ('clever', 'Умный', '[ˈklevə(r)]'),
  ('cold', 'Холодный', '[kəʊld]'),
  ('comfortable', 'Комфортный', '[ˈkʌmftəbl]'),
  ('confident', 'Уверенный', '[ˈkɒnfɪdənt]'),
  ('constant', 'Постоянный', '[ˈkɒnstənt]'),
  ('curious', 'Любопытный', '[ˈkjʊəriəs]'),
  ('dangerous', 'Опасный', '[ˈdeɪndʒərəs]'),
  ('dark', 'Темный', '[dɑːk]'),
  ('deep', 'Глубокий', '[diːp]'),
  ('different', 'Разный', '[ˈdɪfrənt]'),
  ('difficult', 'Трудный', '[ˈdɪfɪkəlt]'),
  ('dirty', 'Грязный', '[ˈdɜːti]'),
  ('easy', 'Легкий', '[ˈiːzi]'),
  ('every', 'Каждый', '[ˈevri]'),
  ('expensive', 'Дорогой', '[ɪkˈspensɪv]'),
  ('exact', 'Точный', '[ɪɡˈzækt]'),
  ('fast', 'Быстрый', '[fɑːst]'),
  ('fair', 'Честный, светлый', '[feə(r)]'),
  ('fine', 'Замечательный', '[faɪn]'),
  ('foreign', 'Иностранный', '[ˈfɒrən]'),
  ('free', 'Свободный', '[friː]'),
  ('fresh', 'Свежий', '[freʃ]'),
  ('full', 'Полный', '[fʊl]'),
  ('funny', 'Забавный', '[ˈfʌni]'),
  ('guilty', 'Виновный', '[ˈɡɪlti]'),
  ('healthy', 'Здоровый', '[ˈhelθi]'),
  ('hard', 'Тяжелый', '[hɑːd]'),
  ('helpful', 'Полезный', '[ˈhelpfl]'),
  ('honest', 'Честный', '[ˈɒnɪst]'),
  ('hot', 'Горячий', '[hɒt]'),
  ('hungry', 'Голодный', '[ˈhʌŋɡri]'),
  ('important', 'Важный', '[ɪmˈpɔːtnt]'),
  ('illegal', 'Нелегальный, незаконный', '[ɪˈliːɡl]'),
  ('impossible', 'Невозможный', '[ɪmˈpɒsəbl]'),
  ('independent', 'Независимый', '[ˌɪndɪˈpendənt]'),
  ('interesting', 'Интересный', '[ˈɪntrəstɪŋ]'),
  ('kind', 'Добрый', '[kaɪnd]'),
  ('legal', 'Законный', '[ˈliːɡl]'),
  ('little', 'Маленький', '[ˈlɪtl]'),
  ('lucky', 'Удачливый', '[ˈlʌki]'),
  ('necessary', 'Необходимый', '[ˈnesəsəri]'),
  ('normal', 'Нормальный', '[ˈnɔːml]'),
  ('old', 'Старый', '[əʊld]'),
  ('opposite', 'Противоположный', '[ˈɒpəzɪt]'),
  ('perfect', 'Идеальный', '[pəˈfekt]'),
  ('poor', 'Бедный', '[pɔː(r)]'),
  ('powerful', 'Мощный', '[ˈpaʊəfl]'),
  ('possible', 'Возможный', '[ˈpɒsəbl]'),
  ('quiet', 'Тихий', '[ˈkwaɪət]'),
  ('rare', 'Редкий', '[reə(r)]'),
  ('recent', 'Недавний', '[ˈriːsnt]'),
  ('relevant', 'Релевантный, актуальный', '[ˈreləvənt]'),
  ('remote', 'Удаленный', '[rɪˈməʊt]'),
  ('safe', 'Безопасный', '[seɪf]'),
  ('short', 'Короткий', '[ʃɔːt]'),
  ('together', 'Вместе', '[təˈɡeðə(r)]'),
('according', 'В соответствии', '[əˈkɔːdɪŋ]'),
('again', 'Снова', '[əˈɡen]'),
('always', 'Всегда', '[ˈɔːlweɪz]'),
('beautifully', 'Красиво', '[ˈbjuːtɪfli]'),
('carefully', 'Осторожно', '[ˈkeə.fəl.i]'),
('correctly', 'Верно, правильно', '[kəˈrektli]'),
('especially', 'Особенно', '[ɪˈspeʃəli]'),
('friendly', 'Дружелюбно', '[ˈfrendli]'),
('indeed', 'Действительно', '[ɪnˈdiːd]'),
('above', 'Выше', '[əˈbʌv]'),
('accidentally', 'Случайно', '[ˌæk.sɪˈden.təl.i]'),
('actually', 'На самом деле', '[ˈæktʃuəli]'),
('badly', 'Плохо', '[ˈbædli]'),
('besides', 'Помимо этого', '[bɪˈsaɪdz]'),
('briefly', 'Кратко', '[ˈbriːfli]'),
('certainly', 'Конечно', '[ˈsɜːtnli]'),
('daily', 'Ежедневно', '[ˈdeɪli]'),
('dreamily', 'Мечтательно', '[ˈdriː.mɪ.li]'),
('even', 'Даже', '[ˈiːvn]'),
('eventually', 'В конце концов', '[ɪˈventʃuəli]'),
('foolishly', 'Глупо', '[ˈfuːlɪʃli]'),
('forward', 'Вперед', '[ˈfɔːwəd]'),
('ever', 'Когда-либо', '[ˈevə(r)]'),
('equally', 'Одинаково', '[ˈiːkwəli]'),
('fortunately', 'К счастью', '[ˈfɔː.tʃən.ət.li]'),
('honestly', 'Честно', '[ˈɒnɪstli]'),
('instead', 'Вместо', '[ɪnˈsted]'),
('inside', 'Внутри', '[ˌɪnˈsaɪd]'),
('also', 'Также', '[ˈɔːlsəʊ]'),
('hardly', 'С трудом', '[ˈhɑːdli]'),
('lately', 'Недавно', '[ˈleɪt.li]'),
('less', 'Меньше', '[les]'),
('loudly', 'Громко, шумно', '[ˈlaʊd.li]'),
('nearly', 'Около', '[ˈnɪəli]'),
('never', 'Никогда', '[ˈnevə(r)]'),
('only', 'Только', '[ˈəʊnli]'),
('once', 'Один раз', '[wʌns]'),
('often', 'Часто', '[ˈɒfn]'),
('perhaps', 'Возможно', '[pəˈhæps]'),
('quickly', 'Быстро', '[ˈkwɪkli]'),
('probably', 'Вероятно', '[ˈprɒbəbli]'),
('rarely', 'Редко', '[ˈreəli]'),
('really', 'Действительно', '[ˈriːəli]'),
('sometimes', 'Иногда', '[ˈsʌmtaɪmz]'),
('yesterday', 'Вчера', '[ˈjestədeɪ]'),
('thus', 'Таким образом', '[ðʌs]'),
('somehow', 'Как-то', '[ˈsʌmhaʊ]'),
('soon', 'Скоро', '[suːn]'),
('regularly', 'Регулярно', '[ˈreɡjələli]'),
('somewhere', 'Где-то', '[ˈsʌmweə(r)]');

INSERT INTO words (word, translation, transcription)
VALUES
('distancing', 'Дистанцирование', '[ˈdɪstənsɪŋ]'),
('isolation', 'Изоляция', '[ˌaɪsəʊˈleɪʃən]'),
('self-care', 'Забота о себе', '[sɛlf-keə]'),
('medication', 'Лекарство', '[ˌmɛdɪˈkeɪʃən]'),
('celebration', 'Мероприятие', '[ˌsɛlɪˈbreɪʃən]'),
('physician', 'Врач, доктор, терапевт', '[fɪˈzɪʃən]'),
('treatment', 'Лечение', '[ˈtriːtmənt]'),
('improvement', 'Улучшение', '[ɪmˈpruːvmənt]'),
('symptom', 'Симптом', '[ˈsɪmptəm]'),
('dismay', 'Огорчение', '[dɪsˈmeɪ]'),
('cancellation', 'Отмена', '[ˌkænsəˈleɪʃən]'),
('suspiciousness', 'Подозрительность', '[səsˈpɪʃəsnəs]'),
('escalation', 'Обострение', '[ˌɛskəˈleɪʃən]'),
('proceeding', 'Разбирательство', '[prəˈsiːdɪŋ]'),
('awareness', 'Осознание', '[əˈweənəs]'),
('responsibility', 'Ответственность', '[rɪsˌpɒnsəˈbɪlɪti]'),
('aftermath', 'Последствие', '[ˈɑːftəmæθ]'),
('weakness', 'Слабость', '[ˈwiːknɪs]'),
('rivalry', 'Противостояние', '[raɪvəlri]'),
('restlessness', 'Беспокойство', '[ˈrɛstlɪsnɪs]'),
('uncertainty', 'Неуверенность', '[ʌnˈsɜːtnti]'),
('stress resistance', 'Стрессоустойчивость', '[strɛs rɪˈzɪstəns]'),
('conscience', 'Совесть', '[kɒnʃəns]'),
('mindfulness', 'Осознанность', '[ˈmaɪndfʊlnəs]'),
('protection', 'Защита', '[prəˈtɛkʃən]'),
('referral', 'Направление', '[rɪˈfɜrəl]'),
('hopelessness', 'Безнадежность', '[ˈhəʊplɪsnɪs]'),
('reliability', 'Надежность', '[rɪˌlaɪəˈbɪlɪti]'),
('verification', 'Проверка', '[ˌvɛrɪfɪˈkeɪʃən]'),
('self-isolation', 'Самоизоляция', '[sɛlf-ˌaɪsəʊˈleɪʃən]'),
('provocation', 'Провокация', '[prɒvəˈkeɪʃən]'),
('prevention', 'Профилактика', '[prɪˈvɛnʃən]'),
('side effect', 'Побочный эффект', '[saɪd ɪˈfɛkt]'),
('vaccination', 'Вакцинация','[ˌvæksɪˈneɪʃən]'),
('immunization', 'Иммунизация', '[ ɪˌmju(ː)naɪˈzeɪʃən]'),
('contradiction', 'Противоречие', '[ˌkɒntrəˈdɪkʃən]'),
('emotion', 'Эмоция', '[ ɪˈməʊʃən]'),
('disagreement', 'Разногласие', '[ˌdɪsəˈgriːmənt]'),
('misunderstanding', 'Недоразумение', '[ ˌmɪsʌndəˈstændɪŋ]'),
('negotiation', 'Переговоры', '[nɪˌgəʊʃɪˈeɪʃən]'),
('downfall', 'Падение', '[ˈdaʊnfɔːl]'),
('setback', 'Неудача', '[ˈsɛtbæk]'),
('bad luck', 'Невезение', '[bæd lʌk]'),
('depression', 'Депрессия', '[dɪˈprɛʃən]'),
('solitude', 'Одиночество', '[ˈsɒlɪtjuːd]'),
('self-blame', 'Самобичевание', '[sɛlf-bleɪm]'),
('disorder', 'Расстройство', '[dɪsˈɔːdə]'),
('instability', 'Нестабильность', '[ɪnstəˈbɪlɪti]'),
('challenge', 'Вызов', '[ˈʧælɪnʤ]'),
('sustainability', 'Устойчивость', '[səsˌteɪnəˈbɪlɪti]'),
('duration', 'Продолжительность', '[djʊəˈreɪʃən]'),
('luckiness', 'Удачливость', '[ˈlʌkɪnəs]'),
('fluke', 'Случайность', '[fluːk]'),
('winning', 'Выигрыш', '[ˈwɪnɪŋ]'),
('lottery', 'Лотерея', '[ˈlɒtəri]'),
('destination', 'Предназначение', '[ˌdɛstɪˈneɪʃən]'),
('advantage', 'Преимущество', '[ədˈvɑːntɪʤ]'),
('win-win', 'Победа', '[wɪn-wɪn]'),
('condition', 'Условие', '[kənˈdɪʃən]'),
('contest', 'Соревнование', '[ˈkɒntɛst]'),
('humbleness', 'Смирение', '[ˈhʌmblnəs]'),
('fearlessness', 'Бесстрашие', '[ˈfɪəlɪsnəs]'),
('hardening', 'Закалка', '[ˈhɑːdnɪŋ]'),
('buoyancy', 'Оживленность', '[ˈbɔɪənsi]'),
('cheerfulness', 'Жизнерадостность', '[ˈʧɪəfʊlnəs]'),
('hospitality', 'Гостеприимство', '[hɒspɪˈtælɪti]'),
('pessimism', 'Пессимизм', '[ˈpɛsɪmɪzm]'),
('morale', 'Дух', '[mɒˈrɑːl]'),
('wisdom', 'Мудрость', '[ˈwɪzdəm]'),
('proficiency', 'Мастерство', '[prəˈfɪʃənsi]'),
('applicant', 'Претендент', '[ˈæplɪkənt]'),
('decisiveness', 'Решительность', '[dɪˈsaɪsɪvnəs]'),
('loophole', 'Лазейка', '[ˈluːphəʊl]'),
('frustration', 'Разочарование', '[frʌsˈtreɪ.ʃən]'),
('knowledge', 'Знание', '[ˈnɒlɪʤ]'),
('decision-making', 'Принятие решения', '[dɪˈsɪʒən-ˈmeɪkɪŋ]'),
('alacrity', 'Аккуратность', '[əˈlækrɪti]'),
('extremity', 'Чрезмерность', '[ɪksˈtrɛmɪti]'),
('background', 'Предпосылка', '[ˈbækgraʊnd]'),
('preparatory', 'Подготовка', '[prɪˈpærətəri]');

INSERT INTO words (word, translation, transcription)
VALUES
('To abolish', 'Упразднять', '[əˈbɒlɪʃ]'),
('To approve', 'Одобрить', '[əˈpruːv]'),
('To boast', 'Хвастаться', '[bəʊst]'),
('To contribute', 'Вносить свой вклад', '[kənˈtrɪbju(ː)t]'),
('To deliver', 'Доставлять', '[dɪˈlɪvə]'),
('To descend', 'Спуститься', '[dɪˈsɛnd]'),
('To concentrate', 'Сосредотачиваться', '[ˈkɒnsəntreɪt]'),
('To distract', 'Отвлекать', '[dɪsˈtrækt]'),
('To torture', 'Мучить', '[ˈtɔːʧə]'),
('To confuse', 'Запутать', '[kənˈfjuːz]'),
('To abandon', 'Бросить', '[əˈbændən]'),
('To escape', 'Убежать', '[ɪsˈkeɪp]'),
('To distribute', 'Распределить', '[dɪsˈtrɪbju(ː)t]'),
('To elaborate', 'Разрабатывать', '[ɪˈlæbərɪt]'),
('To construct', 'Построить', '[kənˈstrʌkt]'),
('To humiliate', 'Унижать', '[hju(ː)ˈmɪlɪeɪt]'),
('To maintain', 'Поддерживать', '[meɪnˈteɪn]'),
('To squeeze', 'Сжать', '[skwiːz]'),
('To delegate', 'Делегировать', '[ˈdɛlɪgɪt]'),
('To transfer', 'Передавать', '[ˈtrænsfə(ː)]'),
('To employ', 'Нанимать', '[ɪmˈplɔɪ]'),
('To catch', 'Поймать', '[kæʧ]'),
('To commit', 'Совершить', '[kəˈmɪt]'),
('To arrange', 'Устроить', '[əˈreɪnʤ]'),
('To implement', 'Внедрить', '[ˈɪmplɪmənt]'),
('To insulate', 'Ограждать', '[ˈɪnsjʊleɪt]'),
('To encourage', 'Стимулировать', '[ɪnˈkʌrɪʤ]'),
('To foster', 'Поощрять', '[ˈfɒstə]'),
('To boost', 'Повышать', '[buːst]'),
('To optimize', 'Оптимизировать', '[ˈɒptɪmaɪz]'),
('To rank', 'Ранжировать', '[ræŋk]'),
('To identify', 'Идентифицировать', '[aɪˈdɛntɪfaɪ]'),
('To empower', 'Наделить полномочиями', '[ɪmˈpaʊə]'),
('To ensure', 'Гарантировать', '[ɪnˈʃʊə]'),
('To accomplish', 'Завершить', '[əˈkɒmplɪʃ]'),
('To customize', 'Настроить', '[ˈkʌstəˌmaɪz]'),
('To localize', 'Локализовать', '[ˈləʊkəlaɪz]'),
('To tailor', 'Приспособить', '[ˈteɪlə]'),
('To validate', 'Удостоверять', '[ˈvælɪdeɪt]'),
('To reserve', 'Зарезервировать', '[rɪˈzɜːv]'),
('To estimate', 'Оценивать', '[ˈɛstɪmɪt]'),
('To consulate', 'Консультировать', '[ˈkɒnsjʊlɪt]'),
('To regard', 'Рассматривать', '[rɪˈgɑːd]'),
('To indicate', 'Указывать', '[ˈɪndɪkeɪt]'),
('To unify', 'Объединять', '[juːnɪfaɪ]'),
('To digitalize', 'Перевести в online-формат', '[ˈdɪdʒɪtəlaɪz]'),
('To expose', 'Подвергать', '[ɪksˈpəʊz]'),
('To idealize', 'Идеализировать', '[ aɪˈdɪəlaɪz]'),
('To navigate', 'Ориентироваться', '[ˈnævɪgeɪt]'),
('To sustain', 'Выдерживать', '[səsˈteɪn]'),
('To constrain', 'Сдерживать', '[kənˈstreɪn]'),
('To evade', 'Обойти', '[ɪˈveɪd]'),
('To purchase', 'Приобретать', '[ˈpɜːʧəs]'),
('To earn', 'Зарабатывать', '[ɜːn]'),
('To make sure', 'Убедиться', '[meɪk ʃʊə]'),
('To prototype', 'Создать прототип', '[ˈprəʊtəʊtaɪp]'),
('To endeavour', 'Стремиться', '[ɪnˈdɛvə]'),
('To blend', 'Смешивать', '[blɛnd]'),
('To prioritize', 'Расставить приоритеты', '[praɪˈɒrɪˌtaɪz]'),
('To mitigate', 'Смягчать', '[ˈmɪtɪgeɪt]'),
('To emphasize', 'Подчеркнуть', '[ˈɛmfəsaɪz]'),
('To observe', 'Наблюдать', '[əbˈzɜːv]'),
('To evolve', 'Развиваться', '[ ɪˈvɒlv]'),
('To incentivize', 'Стимулировать', '[ɪnˈsen.tɪ.vaɪz]'),
('To respond', 'Отвечать', '[rɪsˈpɒnd]'),
('To connect', 'Соединить', '[kəˈnɛkt]'),
('To command', 'Командовать', '[kəˈmɑːnd]'),
('To check-out', 'Проверить', '[ʧɛk-aʊt]'),
('To extend', 'Расширить', '[ɪksˈtɛnd]'),
('To retain', 'Сохранить', '[rɪˈteɪn]'),
('To exhibit', 'Показывать', '[ɪgˈzɪbɪt]'),
('To invent', 'Изобретать', '[ɪnˈvɛnt]'),
('To abridge', 'Ограничивать', '[əˈbrɪʤ]'),
('To self-express', 'Самовыражаться', '[sɛlf-ɪksˈprɛs]'),
('To neglect', 'Пренебрегать', '[nɪˈglɛkt]'),
('To negotiate', 'Вести переговоры', '[nɪˈgəʊʃɪeɪt]'),
('To upgrade', 'Улучшать', '[ʌpˈgreɪd]'),
('To renew', 'Обновить', '[rɪˈnjuː]'),
('To specialize', 'Специализироваться', '[ˈspɛʃəlaɪz]'),
('To balance', 'Уравновешивать', '[ˈbæləns]'),
('To absorb', 'Поглощать', '[əbˈsɔːb]'),
('To overwhelm', 'Переполнять', '[əʊvəˈwɛlm]'),
('To align', 'Выравнивать', '[əˈlaɪn]'),
('To withdraw', 'Отстраниться', '[wɪðˈdrɔː]'),
('To whistle', 'Свистеть', '[ˈwɪsl]'),
('To suspect', 'Подозревать', '[ˈsʌspɛkt]'),
('To surrender', 'Сдаваться', '[səˈrɛndə]'),
('To depend on', 'Зависеть от', '[dɪˈpɛnd ɒn]'),
('To correct', 'Исправлять', '[kəˈrɛkt]'),
('To define', 'Определить', '[dɪˈfaɪn]'),
('To visualize', 'Визуализировать', '[ˈvɪzjʊəlaɪz]'),
('To design', 'Проектировать', '[dɪˈzaɪn]'),
('To minimize', 'Минимизировать', '[ˈmɪnɪmaɪz]'),
('To disturb', 'Беспокоить', '[dɪsˈtɜːb]'),
('To integrate', 'Интегрировать', '[ˈɪntɪgreɪt]'),
('To exchange', 'Обменивать', '[ɪksˈʧeɪnʤ]'),
('To organize', 'Организовать', '[ˈɔːgənaɪz]'),
('To collaborate', 'Сотрудничать', '[kəˈlæbəreɪt]'),
('To embed', 'Встраивать', '[ɪmˈbɛd]'),
('To generate', 'Генерировать', '[ˈʤɛnəreɪt]'),
('Arrogant', 'Заносчивый', '[ˈærəʊgənt]'),
('Civilian', 'Гражданский', '[səˈvɪljən]'),
('Commercial', 'Коммерческий', '[kəˈmɜːʃəl]'),
('Convenient', 'Удобный', '[kənˈviːniənt]'),
('Creative', 'Творческий', '[kri(ː)ˈeɪtɪv]'),
('Naughty', 'Шаловливый', '[ˈnɔːti]'),
('Stationary', 'Стационарный', '[ˈsteɪʃnəri]'),
('Valuable', 'Ценный', '[ˈvæljʊəbl]'),
('Significant', 'Существенный', '[sɪgˈnɪfɪkənt]'),
('Foremost', 'Основной', '[ˈfɔːməʊst]'),
('Recent', 'Недавний', '[ˈriːsnt]'),
('Updated', 'Обновленный', '[ʌpˈdeɪtɪd]'),
('Operational', 'Рабочий', '[ˌɒpəˈreɪʃənl]'),
('Intuitive', 'Интуитивный', '[ɪnˈtju(ː)ɪtɪv]'),
('Essential', 'Важный', '[ɪˈsɛnʃəl]'),
('Numerous', 'Многочисленный', '[ˈnjuːmərəs]'),
('Compliant', 'Соответствующий', '[kəmˈplaɪənt]'),
('Straightforward', 'Прямолинейный', '[streɪtˈfɔːwəd]'),
('Understandable', 'Понятный', '[ʌndəˈstændəbl]'),
('Uncompromising', 'Беспрекословный', '[ʌnˈkɒmprəmaɪzɪŋ]'),
('Distinguished', 'Уважаемый', '[dɪsˈtɪŋgwɪʃt]'),
('Separate', 'Отдельный', '[ˈsɛprɪt]'),
('Outstanding', 'Выдающийся', '[aʊtˈstændɪŋ]'),
('Principal', 'Главный', '[ˈprɪnsəpəl]'),
('Leading', 'Ведущий', '[ˈliːdɪŋ]'),
('Cognitive', 'Познавательный', '[ˈkɒgnɪtɪv]'),
('Cutting-edge', 'Новейший', '[kʌtɪŋ-ɛʤ]'),
('Precise', 'Точный', '[prɪˈsaɪs]'),
('Unmatched', 'Непревзойденный', '[ʌnˈmæʧt]'),
('Reasonable', 'Целесообразный', '[ˈriːznəbl]'),
('Fundamental', 'Основополагающий', '[ˌfʌndəˈmɛntl]'),
('Brilliant', 'Блестящий', '[ˈbrɪljənt]'),
('Inflexible', 'Непогрешимый', '[ɪnˈflɛksəbl]'),
('Crucial', 'Критический', '[ɪnˈflɛksəbl]'),
('Contemporary', 'Актуальный', '[kənˈtɛmpərəri]'),
('Duplicated', 'Дублированный', '[ˈdjuːplɪkeɪtɪd]'),
('Tedious', 'Утомительный', '[ˈtiːdiəs]'),
('Multiple', 'Многочисленный', '[ˈmʌltɪpl]'),
('Individual', 'Индивидуальный', '[ɪndɪˈvɪdjʊəl]'),
('Fitting', 'Подходящий', '[ˈfɪtɪŋ]'),
('Monotonous', 'Однообразный', '[məˈnɒtnəs]'),
('Ruthless', 'Бесчеловечный', '[ˈruːθlɪs]'),
('Multi-channel', 'Многоканальный', '[ˈmʌltɪ-ˈʧænl]'),
('Astonishing', 'Поразительный', '[əsˈtɒnɪʃɪŋ]'),
('Ambitious', 'Честолюбивый', '[æmˈbɪʃəs]'),
('Captivating', 'Захватывающий', '[ˈkæptɪveɪtɪŋ]'),
('Profound', 'Глубокомысленный', '[prəˈfaʊnd]'),
('Qualified', 'Квалифицированный', '[ˈkwɒlɪfaɪd]'),
('Remarkable', 'Примечательный', '[rɪˈmɑːkəbl]'),
('Additional', 'Дополнительный', '[əˈdɪʃənl]'),
('Burning', 'Жгучий', '[ˈbɜːnɪŋ]'),
('Unassuming', 'Непритязательный', '[ˌʌnəˈsjuːmɪŋ]'),
('Meaningful', 'Осмысленный', '[ˈmiːnɪŋfʊl]'),
('Private', 'Частный', '[ˈpraɪvɪt]'),
('Careful', 'Осторожный', '[ˈkeəfʊl]'),
('Obscure', 'Непонятный', '[əbˈskjʊə]'),
('Accomplished', 'Состоятельный', '[əˈkɒmplɪʃt]'),
('Ridiculous', 'Смешной', '[rɪˈdɪkjʊləs]'),
('Contemptuous', 'Презрительный', '[kənˈtɛmptjʊəs]'),
('Fashionable', 'Модный', '[ˈfæʃnəbl]'),
('Invariably', 'Неизменно', '[ɪnˈveərɪəbli]'),
('Intermittently', 'Иногда', '[ɪntə(ː)ˈmɪtəntli]'),
('Infrequently', 'Редко', '[ɪntə(ː)ˈmɪtəntli]'),
('Predominantly', 'Преимущественно', '[prɪˈdɒmɪnəntli]'),
('Elsewhere', 'Где-нибудь', '[ˈɛlsˈweə]'),
('Scarcely', 'Едва', '[ ˈskeəsli]'),
('Otherwise', 'Иначе', '[ˈʌðəwaɪz]'),
('Quickly', 'Быстро', '[ˈkwɪkli]'),
('Quietly', 'Тихо', '[ˈkwaɪətli]'),
('Moreover', 'Более того', '[mɔːˈrəʊvə]'),
('Nevertheless', 'Тем не менее', '[ˌnɛvəðəˈlɛs]'),
('Somewhat', 'До некоторой степени', '[ˈsʌmwɒt]'),
('Cheerfully', 'Весело', '[ˈʧɪəfʊli]'),
('Clumsily', 'Неуклюже', '[klʌmzɪli]'),
('In vain', 'Напрасно', '[ɪn veɪn]'),
('At once', 'Немедленно', '[æt wʌns]'),
('Casually', 'Случайно', '[ˈkæʒjʊəli]'),
('Since that', 'С тех пор', '[sɪns ðæt]'),
('By all means', 'Во что бы то ни стало', '[baɪ ɔːl miːnz]'),
('Readily', 'Охотно', '[ˈrɛdɪli]'),
('Outside', 'Снаружи', '[ˌaʊtˈsaɪd]'),
('Besides', 'Кроме того', '[bɪˈsaɪdz]'),
('Once', 'Однажды', '[wʌns]'),
('However', 'Однако', '[haʊˈɛvə]'),
('Yet', 'Еще', '[jɛt]'),
('Foolishly', 'Глупо', '[ˈfuːlɪʃli]'),
('Clearly', 'Очевидно', '[ˈklɪəli]'),
('Actually', 'Вообще-то', '[ˈækʧʊəli]'),
('Completely', 'Абсолютно', '[kəmˈpliːtli]'),
('Extremely', 'Безумно', '[ɪksˈtriːmli]'),
('Nearby', 'Неподалеку', '[ˈnɪəbaɪ]'),
('Unmistakable', 'Безошибочно', '[ʌnmɪsˈteɪkəbl]'),
('Accurately', 'Точно', '[ˈækjʊrɪtli]'),
('Definitely', 'Абсолютно', '[ˈdɛfɪnɪtli]'),
('Relentlessly', 'Безостановочно', '[rɪˈlɛntlɪsli]'),
('Incredibly', 'Невероятно', '[ɪnˈkrɛdəbli]'),
('Decidedly', 'Решительно', '[dɪˈsaɪdɪdli]'),
('Firmly', 'Уверенно', '[ˈfɜːmli]'),
('Carelessly', 'Беспечно', '[ˈkeəlɪsli]'),
('Nevertheless', 'Тем не менее', '[nɛvəðəˈlɛs]'),
('addiction', 'Зависимость', '[əˈdɪkʃ(ə)n]'),
('amateur', 'Любитель', '[ˈæmətə(ː)]'),
('ambivalence', 'Нерешительность', '[æmˈbɪvələns]'),
('commission', 'Поручение', '[kəˈmɪʃən]'),
('confidence', 'Уверенность', '[ˈkɒnfɪdəns]'),
('craving', 'Жажда', '[ˈkreɪvɪŋ]'),
('district', 'Район', '[ˈdɪstrɪkt]'),
('evidence', 'Доказательство', '[ˈɛvɪdəns]'),
('honesty', 'Честность', '[ˈɒnɪsti]'),
('circumstance', 'Событие', '[ˈsɜːkəmstəns]'),
('kindness', 'Доброта', '[ˈkaɪndnɪs]'),
('justice', 'Справедливость', '[ˈʤʌstɪs]'),
('disgust', 'Отвращение', '[dɪsˈgʌst]'),
('suggestion', 'Идея', '[səˈʤɛsʧən]'),
('nobility', 'Достоинство', '[nəʊˈbɪlɪti]'),
('commotion', 'Суета', '[kəˈməʊʃən]'),
('adherence', 'Приверженность', '[ədˈhɪərəns]'),
('devotion', 'Преданность', '[dɪˈvəʊʃən]'),
('enticement', 'Приманка', '[ ɪnˈtaɪsmənt]'),
('attractiveness', 'Привлекательность', '[ əˈtræktɪvnəs]'),
('freedom-loving', 'Свободолюбие', '[ˈfriːdəm-ˈlʌvɪŋ]'),
('rebel', 'Бунтарь', '[ˈrɛbl]'),
('influence', 'Влияние', '[ ˈɪnflʊəns]'),
('sway', 'Колебание', '[sweɪ]'),
('willpower', 'Сила воли', '[ˈwɪlˌpaʊə]'),
('inequality', 'Неравенство', '[ˌɪni(ː)ˈkwɒlɪti]'),
('violence', 'Жестокость', '[ˈvaɪələns]'),
('bullying', 'Издевательство', '[ˈbʊliɪŋ]'),
('godliness', 'Благочестие', '[ˈgɒdlɪnɪs]'),
('compassion', 'Сострадание', '[kəmˈpæʃən]'),
('inclusivity', 'Инклюзивность', '[ɪnˌkluːˈsɪvətɪ]'),
('reciprocity', 'Обоюдность', '[rɛsɪˈprɒsɪti]'),
('friskiness', 'Игривость', '[ˈfrɪskɪnəs]'),
('fervor', 'Задор', '[ˈfɜːvə]'),
('youth', 'Юноша', '[juːθ]'),
('adolescence', 'Отрочество', '[ædəʊˈlɛsns]'),
('prerequisite', 'Предпосылка', '[ˌpriːˈrɛkwɪzɪt]'),
('fortune', 'Удача', '[ˈfɔːʧən]'),
('stubbornness', 'Упрямство', '[ˈstʌbənnɪs]'),
('disappointment', 'Разочарование', '[dɪsəˈpɔɪntmənt]');