-- Глаголы VERB
INSERT INTO words (word, translation, transcription, wordLevel, wordType)
VALUES ('To appear', 'Появлятся', '[əˈpɪə]', 'A2', 'VERB'),
('To cancel', 'Отменять', '[ˈkænsəl]', 'A2', 'VERB'), 
('To bite', 'Кусать;Укусить', '[baɪt]', 'A2', 'VERB'), 
('To regret', 'Сожалеть', '[rɪˈgrɛt]', 'A2', 'VERB'), 
('To blow', 'Дуть (о ветре);Развеять;Раздувать', '[bləʊ]', 'A2', 'VERB'), 
('To compose', 'Составлять', '[kəmˈpəʊz]', 'A2', 'VERB'), 
('To congratulate', 'Поздравлять', '[kənˈgrætjʊleɪt]', 'A2', 'VERB'), 
('To correct', 'Исправлять', '[kəˈrɛkt]', 'A2', 'VERB'), 
('To fall asleep', 'Засыпать', '[fɔːl əˈsliːp]', 'A2', 'VERB'), 
('To burn', 'Гореть', '[bɜːn]', 'A2', 'VERB'), 
('To invent', 'Придумать;Изобретать', '[ɪnˈvɛnt]', 'A2', 'VERB'), 
('To mention', 'Упоминать;Заметить;Отметить', '[ˈmɛnʃən]', 'A2', 'VERB'), 
('To suppose', 'Предполагать', '[səˈpəʊz]', 'A2', 'VERB'), 
('To suggest', 'Предлагать;Намекать', '[səˈʤɛst]', 'A2', 'VERB'),
('To consider', 'Размышлять;Учитывать', '[kənˈsɪdə]', 'A2', 'VERB'), 
('To escape', 'Сбегать;Убегать', '[ɪsˈkeɪp]', 'A2', 'VERB'), 
('To publish', 'Публиковать', '[ˈpʌblɪʃ]', 'A2', 'VERB'), 
('To solve', 'Решить;Разгадать', '[sɒlv]', 'A2', 'VERB'), 
('To tidy up', 'Убираться;Наводить порядок', '[ˈtaɪdi ʌp]', 'A2', 'VERB'), 
('To win', 'Выиграть', '[‘taɪdi ʌp]', 'A2', 'VERB'), 
('To swallow', 'Глотать', '[ˈswɒləʊ]', 'A2', 'VERB'), 
('To follow', 'Следовать', '[ˈfɒləʊ]', 'A2', 'VERB'), 
('To abandon', 'Покидать;Оставлять', '[əˈbændən]', 'A2', 'VERB'), 
('To be able', 'Быть в состоянии', '[biː ˈeɪbl]', 'A2', 'VERB'), 
('To abuse', 'Оскорблять', '[əˈbjuːs]', 'A2', 'VERB'), 
('To accelerate', 'Ускорять', '[əkˈsɛləreɪt]', 'A2', 'VERB'), 
('To reveal', 'Раскрывать', '[rɪˈviːl]', 'A2', 'VERB'), 
('To consist of', 'Состоять из', '[kənˈsɪst ɒv]', 'A2', 'VERB'), 
('To include', 'Включать', '[ɪnˈkluːd]', 'A2', 'VERB'), 
('To guess', 'Думать;Предполагать', '[gɛs]', 'A2', 'VERB'), 
('To accept', 'Одобрять;Согласовать', '[əkˈsɛpt]', 'A2', 'VERB'), 
('To formulate', 'Формулировать', '[ˈfɔːmjʊleɪt]', 'A2', 'VERB'), 
('To form', 'Формировать', '[fɔːm]', 'A2', 'VERB'), 
('To achieve', 'Достигать', '[əˈʧiːv]', 'A2', 'VERB'), 
('To acknowledge', 'Подтверждать', '[əkˈnɒlɪʤ]', 'A2', 'VERB'), 
('To act', 'Действовать', '[ækt]', 'A2', 'VERB'), 
('To adhere', 'Придерживаться', '[ədˈhɪə]', 'A2', 'VERB'),
('To admire', 'Восхищаться', '[ədˈmaɪə]', 'A2', 'VERB'), 
('To adjust', 'Адаптировать;Настроить', '[əˈʤʌst]', 'A2', 'VERB'), 
('To advise', 'Советовать', '[ədˈvaɪz]', 'A2', 'VERB'), 
('To allow', 'Позволять;Разрешать', '[əˈlaʊ]', 'A2', 'VERB'), 
('To improve', 'Улучшать', '[ɪmˈpruːv]', 'A2', 'VERB'), 
('To edit', 'Редактировать', '[ˈɛdɪt]', 'A2', 'VERB'), 
('To conclude', 'Включать в себя', '[kənˈkluːd]', 'A2', 'VERB'), 
('To settle', 'Располагаться;Поселиться', '[ˈsɛtl]', 'A2', 'VERB'), 
('To handle', 'Справиться', '[ˈhændl]', 'A2', 'VERB'), 
('To boost', 'Увеличить;Поддержать', '[buːst]', 'A2', 'VERB'), 
('To amplify', 'Усилить;Расширить', '[ˈæmplɪfaɪ]', 'A2', 'VERB'), 
('To appeal', 'Просить;Обращаться', '[əˈpiːl]', 'A2', 'VERB'), 
('To assemble', 'Собираться;Созывать', '[əˈsɛmbl]', 'A2', 'VERB'), 
('To assess', 'Оценивать;Рассматривать', '[əˈsɛs]', 'A2', 'VERB'), 
('To assist', 'Присутствовать;Помогать', '[əˈsɪst]', 'A2', 'VERB'), 
('To astonish', 'Удивлять', '[əsˈtɒnɪʃ]', 'A2', 'VERB'), 
('To assure', 'Убеждать;Заверять', '[əˈʃʊə]', 'A2', 'VERB'), 
('To avoid', 'Избегать', '[əˈvɔɪd]', 'A2', 'VERB'), 
('To await', 'Ожидать', '[əˈweɪt]', 'A2', 'VERB'), 
('To pick up', 'Подбирать;Забирать', '[pɪk ʌp]', 'A2', 'VERB'), 
('To cross off', 'Вычеркивать', '[krɒs ɒf]', 'A2', 'VERB'), 
('To claim', 'Утверждать;Заявлять', '[kleɪm]', 'A2', 'VERB'), 
('To hurry up', 'Торопиться', '[ˈhʌri ʌp]', 'A2', 'VERB'), 
('To find out', 'Находить', '[faɪnd aʊt]', 'A2', 'VERB'), 
('To divide', 'Делить;Разделять', '[dɪˈvaɪd]', 'A2', 'VERB'), 
('To bark', 'Лаять', '[bɑːk]', 'A2', 'VERB'), 
('To bathe', 'Купаться', '[beɪð]', 'A2', 'VERB'), 
('To beat', 'Бить;Превосходить', '[biːt]', 'A2', 'VERB'), 
('To blackmail', 'Шантажировать', '[ˈblækmeɪl]', 'A2', 'VERB'),
('To spent', 'Тратить', '[spɛnt]', 'A2', 'VERB'), 
('To send', 'Посылать', '[sɛnd]', 'A2', 'VERB'), 
('To laugh', 'Смеяться', '[lɑːf]', 'A2', 'VERB'), 
('To struggle', 'Бороться', '[ˈstrʌgl]', 'A2', 'VERB'), 
('To motivate', 'Мотивировать', '[ˈməʊtɪveɪt]', 'A2', 'VERB'), 
('To perceive', 'Воспринимать', '[pəˈsiːv ]', 'A2', 'VERB'), 
('To receive', 'Получать', '[rɪˈsiːv]', 'A2', 'VERB'), 
('To recognize', 'Распознавать', '[ˈrɛkəgnaɪz]', 'A2', 'VERB'), 
('To remain', 'Напоминать', '[rɪˈmeɪn]', 'A2', 'VERB'), 
('To retain', 'Удержать', '[ rɪˈteɪn]', 'A2', 'VERB'), 
('To remember', 'Помнить;Запоминать', '[rɪˈmɛmbə]', 'A2', 'VERB'), 
('To observed', 'Исследовать', '[əbˈzɜːvd]', 'A2', 'VERB'), 
('To fight', 'Драться', '[faɪt]', 'A2', 'VERB'), 
('To renew', 'Обновлять', '[rɪˈnju]', 'A2', 'VERB'), 
('To keep calm', 'Успокаиваться', '[kiːp kɑːm]', 'A2', 'VERB'), 
('To break up', 'Разрушать;Расходиться', '[breɪk ʌp]', 'A2', 'VERB'), 
('To focus', 'Фокусироваться', '[ˈfəʊkəs]', 'A2', 'VERB'), 
('To perform', 'Исполнять обязанности', '[pəˈfɔːm]', 'A2', 'VERB'), 
('To offer', 'Предлагать', '[ˈɒfə]', 'A2', 'VERB'), 
('To display', 'Отображать', '[dɪsˈpleɪ]', 'A2', 'VERB'), 
('To behave', 'Вести себя', '[bɪˈheɪv]', 'A2', 'VERB'), 
('To get rid', 'Избавляться', '[gɛt rɪd]', 'A2', 'VERB'), 
('To squeeze', 'Выжимать', '[skwiːz]', 'A2', 'VERB'), 
('To release', 'Выпускать;Публиковать', '[rɪˈliːs]', 'A2', 'VERB'), 
('To push', 'Толкать', '[pʊʃ]', 'A2', 'VERB'), 
('To foster', 'Поощрять', '[ˈfɒstə]', 'A2', 'VERB'), 
('To enhance', 'Расширять;Поощрять', '[ɪnˈhɑːns]', 'A2', 'VERB'), 
('To develop', 'Развивать;Разрабатывать', '[dɪˈvɛləp]', 'A2', 'VERB'), 
('To envelop', 'Окутывать;Обволакивать', '[ɪnˈvɛləp]', 'A2', 'VERB'), 
('To obtain', 'Получить;Добиться;Приобрести', '[əbˈteɪn]', 'A2', 'VERB'), 
('To investigate', 'Расследовать', '[ɪnˈvɛstɪgeɪt]', 'A2', 'VERB'), 
('To adore', 'Обожать', '[əˈdɔː]', 'A2', 'VERB'), 
('To block out', 'Блокировать', '[blɒk aʊt]', 'A2', 'VERB'), 
('To boil', 'Кипеть', '[bɔɪl]', 'A2', 'VERB'),
('To bother', 'Побеспокоить;Заморачиваться', '[ˈbɒðə]', 'A2', 'VERB'), 
('To breathe', 'Дышать', '[briːð]', 'A2', 'VERB'), 
('To brew', 'Варить;Заваривать', '[bruː]', 'A2', 'VERB'), 
('To celebrate', 'Отмечать', '[ˈsɛlɪbreɪt]', 'A2', 'VERB'), 
('To broadcast', 'Вещать;Транслировать', '[ˈbrɔːdkɑːst]', 'A2', 'VERB'), 
('To modify', 'Изменять;Модифицировать', '[ˈmɒdɪfaɪ]', 'A2', 'VERB'), 
('To bump', 'Ударять', '[bʌmp]', 'A2', 'VERB'), 
('To buzz', 'Жужжать', '[bʌz]', 'A2', 'VERB'), 
('To lead', 'Вести;Лидировать;Быть лидером', '[liːd]', 'A2', 'VERB'), 
('To call back', 'Перезвонить', '[kɔːl bæk]', 'A2', 'VERB'), 
('To waste', 'Тратить впустую;Мусорить', '[weɪst]', 'A2', 'VERB'), 
('To take care', 'Заботиться', '[teɪk keə]', 'A2', 'VERB'), 
('To carry out', 'Выполнять;Осуществлять', '[ˈkæri aʊt]', 'A2', 'VERB'), 
('To carve', 'Вырезать', '[kɑːv]', 'A2', 'VERB'), 
('To cease', 'Прекратить', '[siːs]', 'A2', 'VERB'),
('To collaborate', 'Сотрудничать', '[kəˈlæbəreɪt]', 'A2', 'VERB'), 
('To reward', 'Награждать', '[rɪˈwɔːd]', 'A2', 'VERB'), 
('To come back', 'Возвращаться', '[kʌm bæk]', 'A2', 'VERB'), 
('To relate', 'Относиться;Касаться', '[rɪˈleɪt]', 'A2', 'VERB'), 
('To upgrade', 'Обновлять', '[ʌpˈgreɪd]', 'A2', 'VERB'), 
('To restore', 'Восстановить', '[rɪsˈtɔː]', 'A2', 'VERB'), 
('To describe', 'Описывать', '[dɪsˈkraɪb]', 'A2', 'VERB'), 
('To share', 'Делиться', '[ʃeə]', 'A2', 'VERB'), 
('To increase', 'Увеличивать', '[ˈɪnkriːs]', 'A2', 'VERB'), 
('To automate', 'Автоматизировать', '[ˈɔːtəmeɪt]', 'A2', 'VERB'), 
('To manage', 'Управлять', '[ˈmænɪʤ]', 'A2', 'VERB'), 
('To provide', 'Обеспечивать', '[prəˈvaɪd]', 'A2', 'VERB'), 
('To integrate', 'Соединять;Интегрировать', '[ˈɪntɪgreɪt]', 'A2', 'VERB'), 
('To realize', 'Реализовывать;Осуществлять', '[ˈrɪəlaɪz]', 'A2', 'VERB'), 
('To remind', 'Напоминать', '[ˈrɪmaɪnd]', 'A2', 'VERB'), 
('To install', 'Устанавливать', '[ɪnˈstɔːl]', 'A2', 'VERB'), 
('To download', 'Загружать', '[daʊnˈləʊd]', 'A2', 'VERB'), 
('To unpack', 'Распаковать', '[ʌnˈpæk]', 'A2', 'VERB'), 
('To engage', 'Увлечь;Привлечь', '[ɪnˈgeɪʤ]', 'A2', 'VERB'), 
('To create', 'Создавать', '[kri(ː)ˈeɪt]', 'A2', 'VERB'), 
('To prefer', 'Предпочитать', '[priˈfɜː]', 'A2', 'VERB'), 
('To inspire', 'Вдохновлять', '[ɪnˈspaɪə]', 'A2', 'VERB'), 
('To apply', 'Применять', '[əˈplaɪ]', 'A2', 'VERB'),
('To simplify', 'Упрощать', '[ˈsɪmplɪfaɪ]', 'A2', 'VERB'), 
('To strive', 'Стремиться', '[straɪv]', 'A2', 'VERB'), 
('To arrive', 'Прибывать', '[əˈraɪv]', 'A2', 'VERB'), 
('To enable', 'Разрешить;Включить', '[ɪˈneɪbl]', 'A2', 'VERB'), 
('To support', 'Поддерживать', '[səˈpɔːt]', 'A2', 'VERB'), 
('To allot', 'Выделить', '[əˈlɒt]', 'A2', 'VERB'), 
('To empower', 'Разрешать;Уполномочить', '[ɪmˈpaʊə]', 'A2', 'VERB'), 
('To overwhelm', 'Переполнять', '[əʊvəˈwɛlm]', 'A2', 'VERB'), 
('To fulfill', 'Выполнять', '[fʊlˈfɪl]', 'A2', 'VERB'), 
('To take over', 'Принять на себя', '[teɪk ˈəʊvə]', 'A2', 'VERB'), 
('To encourage', 'Поощрять', '[ɪnˈkʌrɪʤ]', 'A2', 'VERB'), 
('To stimulate', 'Стимулировать', '[ˈstɪmjʊleɪt]', 'A2', 'VERB'), 
('To cause', 'Вызывать', '[kɔːz]', 'A2', 'VERB'), 
('To deal', 'Справляться', '[diːl]', 'A2', 'VERB'), 
('To reach', 'Достигать', '[riːʧ]', 'A2', 'VERB'), 
('To touch', 'Прикасаться', '[tʌʧ]', 'A2', 'VERB'), 
('To attain', 'Достигать;Получать', '[əˈteɪn]', 'A2', 'VERB'), 
('To require', 'Запрашивать;Требовать', '[rɪˈkwaɪə]', 'A2', 'VERB'), 
('To figure out', 'Разбираться', '[ˈfɪgər aʊt]', 'A2', 'VERB'), 
('To forgive', 'Прощать', '[fəˈgɪv]', 'A2', 'VERB'), 
('To light', 'Освещать;Светить', '[laɪt]', 'A2', 'VERB'), 
('To shine', 'Сиять', '[ʃaɪn]', 'A2', 'VERB'), 
('To spread', 'Распространять', '[sprɛd]', 'A2', 'VERB'), 
('To throw', 'Бросать', '[θrəʊ]', 'A2', 'VERB'), 
('To spoil', 'Испортить', '[spɔːɪl]', 'A2', 'VERB'),
('To split', 'Разбить;Разделить', '[splɪt]', 'A2', 'VERB'), 
('To go mad', 'Сходить с ума', '[gəʊ mæd]', 'A2', 'VERB'), 
('To steal', 'Украсть', '[stiːl]', 'A2', 'VERB'), 
('To smell', 'Пахнуть', '[smɛl]', 'A2', 'VERB');