-- Глаголы VERB
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES ('To appear', 'Появлятся', '[əˈpɪə]', 'A2', 'VERB'),
('To cancel', 'Отменять', '[ˈkænsəl]', 'A2', 'VERB'), 
('To bite', 'Кусать;Укусить', '[baɪt]', 'A2', 'VERB'), 
('To regret', 'Сожалеть', '[rɪˈgrɛt]', 'A2', 'VERB'), 
('To blow', 'Дуть (о ветре);Развеять;Раздувать', '[bləʊ]', 'A2', 'VERB'), 
('To compose', 'Составлять', '[kəmˈpəʊz]', 'A2', 'VERB'), 
('To congratulate', 'Поздравлять', '[kənˈgrætjʊleɪt]', 'A2', 'VERB'), 
('To correct', 'Исправлять', '[kəˈrɛkt]', 'A2', 'VERB'), 
('To fall asleep', 'Засыпать', '[fɔːl əˈsliːp]', 'A2', 'VERB'), 
('To burn', 'Гореть', '[bɜːn]', 'A2', 'VERB'), 
('To invent', 'Придумать;Изобретать', '[ɪnˈvɛnt]', 'A2', 'VERB'), 
('To mention', 'Упоминать;Заметить;Отметить', '[ˈmɛnʃən]', 'A2', 'VERB'), 
('To suppose', 'Предполагать', '[səˈpəʊz]', 'A2', 'VERB'), 
('To suggest', 'Предлагать;Намекать', '[səˈʤɛst]', 'A2', 'VERB'),
('To consider', 'Размышлять;Учитывать', '[kənˈsɪdə]', 'A2', 'VERB'), 
('To escape', 'Сбегать;Убегать', '[ɪsˈkeɪp]', 'A2', 'VERB'), 
('To publish', 'Публиковать', '[ˈpʌblɪʃ]', 'A2', 'VERB'), 
('To solve', 'Решить;Разгадать', '[sɒlv]', 'A2', 'VERB'), 
('To tidy up', 'Убираться;Наводить порядок', '[ˈtaɪdi ʌp]', 'A2', 'VERB'), 
('To win', 'Выиграть', '[‘taɪdi ʌp]', 'A2', 'VERB'), 
('To swallow', 'Глотать', '[ˈswɒləʊ]', 'A2', 'VERB'), 
('To follow', 'Следовать', '[ˈfɒləʊ]', 'A2', 'VERB'), 
('To abandon', 'Покидать;Оставлять', '[əˈbændən]', 'A2', 'VERB'), 
('To be able', 'Быть в состоянии', '[biː ˈeɪbl]', 'A2', 'VERB'), 
('To abuse', 'Оскорблять', '[əˈbjuːs]', 'A2', 'VERB'), 
('To accelerate', 'Ускорять', '[əkˈsɛləreɪt]', 'A2', 'VERB'), 
('To reveal', 'Раскрывать', '[rɪˈviːl]', 'A2', 'VERB'), 
('To consist of', 'Состоять из', '[kənˈsɪst ɒv]', 'A2', 'VERB'), 
('To include', 'Включать', '[ɪnˈkluːd]', 'A2', 'VERB'), 
('To guess', 'Думать;Предполагать', '[gɛs]', 'A2', 'VERB'), 
('To accept', 'Одобрять;Согласовать', '[əkˈsɛpt]', 'A2', 'VERB'), 
('To formulate', 'Формулировать', '[ˈfɔːmjʊleɪt]', 'A2', 'VERB'), 
('To form', 'Формировать', '[fɔːm]', 'A2', 'VERB'), 
('To achieve', 'Достигать', '[əˈʧiːv]', 'A2', 'VERB'), 
('To acknowledge', 'Подтверждать', '[əkˈnɒlɪʤ]', 'A2', 'VERB'), 
('To act', 'Действовать', '[ækt]', 'A2', 'VERB'), 
('To adhere', 'Придерживаться', '[ədˈhɪə]', 'A2', 'VERB'),
('To admire', 'Восхищаться', '[ədˈmaɪə]', 'A2', 'VERB'), 
('To adjust', 'Адаптировать;Настроить', '[əˈʤʌst]', 'A2', 'VERB'), 
('To advise', 'Советовать', '[ədˈvaɪz]', 'A2', 'VERB'), 
('To allow', 'Позволять;Разрешать', '[əˈlaʊ]', 'A2', 'VERB'), 
('To improve', 'Улучшать', '[ɪmˈpruːv]', 'A2', 'VERB'), 
('To edit', 'Редактировать', '[ˈɛdɪt]', 'A2', 'VERB'), 
('To conclude', 'Включать в себя', '[kənˈkluːd]', 'A2', 'VERB'), 
('To settle', 'Располагаться;Поселиться', '[ˈsɛtl]', 'A2', 'VERB'), 
('To handle', 'Справиться', '[ˈhændl]', 'A2', 'VERB'), 
('To boost', 'Увеличить;Поддержать', '[buːst]', 'A2', 'VERB'), 
('To amplify', 'Усилить;Расширить', '[ˈæmplɪfaɪ]', 'A2', 'VERB'), 
('To appeal', 'Просить;Обращаться', '[əˈpiːl]', 'A2', 'VERB'), 
('To assemble', 'Собираться;Созывать', '[əˈsɛmbl]', 'A2', 'VERB'), 
('To assess', 'Оценивать;Рассматривать', '[əˈsɛs]', 'A2', 'VERB'), 
('To assist', 'Присутствовать;Помогать', '[əˈsɪst]', 'A2', 'VERB'), 
('To astonish', 'Удивлять', '[əsˈtɒnɪʃ]', 'A2', 'VERB'), 
('To assure', 'Убеждать;Заверять', '[əˈʃʊə]', 'A2', 'VERB'), 
('To avoid', 'Избегать', '[əˈvɔɪd]', 'A2', 'VERB'), 
('To await', 'Ожидать', '[əˈweɪt]', 'A2', 'VERB'), 
('To pick up', 'Подбирать;Забирать', '[pɪk ʌp]', 'A2', 'VERB'), 
('To cross off', 'Вычеркивать', '[krɒs ɒf]', 'A2', 'VERB'), 
('To claim', 'Утверждать;Заявлять', '[kleɪm]', 'A2', 'VERB'), 
('To hurry up', 'Торопиться', '[ˈhʌri ʌp]', 'A2', 'VERB'), 
('To find out', 'Находить', '[faɪnd aʊt]', 'A2', 'VERB'), 
('To divide', 'Делить;Разделять', '[dɪˈvaɪd]', 'A2', 'VERB'), 
('To bark', 'Лаять', '[bɑːk]', 'A2', 'VERB'), 
('To bathe', 'Купаться', '[beɪð]', 'A2', 'VERB'), 
('To beat', 'Бить;Превосходить', '[biːt]', 'A2', 'VERB'), 
('To blackmail', 'Шантажировать', '[ˈblækmeɪl]', 'A2', 'VERB'),
('To spent', 'Тратить', '[spɛnt]', 'A2', 'VERB'), 
('To send', 'Посылать', '[sɛnd]', 'A2', 'VERB'), 
('To laugh', 'Смеяться', '[lɑːf]', 'A2', 'VERB'), 
('To struggle', 'Бороться', '[ˈstrʌgl]', 'A2', 'VERB'), 
('To motivate', 'Мотивировать', '[ˈməʊtɪveɪt]', 'A2', 'VERB'), 
('To perceive', 'Воспринимать', '[pəˈsiːv ]', 'A2', 'VERB'), 
('To receive', 'Получать', '[rɪˈsiːv]', 'A2', 'VERB'), 
('To recognize', 'Распознавать', '[ˈrɛkəgnaɪz]', 'A2', 'VERB'), 
('To remain', 'Напоминать', '[rɪˈmeɪn]', 'A2', 'VERB'), 
('To retain', 'Удержать', '[ rɪˈteɪn]', 'A2', 'VERB'), 
('To remember', 'Помнить;Запоминать', '[rɪˈmɛmbə]', 'A2', 'VERB'), 
('To observed', 'Исследовать', '[əbˈzɜːvd]', 'A2', 'VERB'), 
('To fight', 'Драться', '[faɪt]', 'A2', 'VERB'), 
('To renew', 'Обновлять', '[rɪˈnju]', 'A2', 'VERB'), 
('To keep calm', 'Успокаиваться', '[kiːp kɑːm]', 'A2', 'VERB'), 
('To break up', 'Разрушать;Расходиться', '[breɪk ʌp]', 'A2', 'VERB'), 
('To focus', 'Фокусироваться', '[ˈfəʊkəs]', 'A2', 'VERB'), 
('To perform', 'Исполнять обязанности', '[pəˈfɔːm]', 'A2', 'VERB'), 
('To offer', 'Предлагать', '[ˈɒfə]', 'A2', 'VERB'), 
('To display', 'Отображать', '[dɪsˈpleɪ]', 'A2', 'VERB'), 
('To behave', 'Вести себя', '[bɪˈheɪv]', 'A2', 'VERB'), 
('To get rid', 'Избавляться', '[gɛt rɪd]', 'A2', 'VERB'), 
('To squeeze', 'Выжимать', '[skwiːz]', 'A2', 'VERB'), 
('To release', 'Выпускать;Публиковать', '[rɪˈliːs]', 'A2', 'VERB'), 
('To push', 'Толкать', '[pʊʃ]', 'A2', 'VERB'), 
('To foster', 'Поощрять', '[ˈfɒstə]', 'A2', 'VERB'), 
('To enhance', 'Расширять;Поощрять', '[ɪnˈhɑːns]', 'A2', 'VERB'), 
('To develop', 'Развивать;Разрабатывать', '[dɪˈvɛləp]', 'A2', 'VERB'), 
('To envelop', 'Окутывать;Обволакивать', '[ɪnˈvɛləp]', 'A2', 'VERB'), 
('To obtain', 'Получить;Добиться;Приобрести', '[əbˈteɪn]', 'A2', 'VERB'), 
('To investigate', 'Расследовать', '[ɪnˈvɛstɪgeɪt]', 'A2', 'VERB'), 
('To adore', 'Обожать', '[əˈdɔː]', 'A2', 'VERB'), 
('To block out', 'Блокировать', '[blɒk aʊt]', 'A2', 'VERB'), 
('To boil', 'Кипеть', '[bɔɪl]', 'A2', 'VERB'),
('To bother', 'Побеспокоить;Заморачиваться', '[ˈbɒðə]', 'A2', 'VERB'), 
('To breathe', 'Дышать', '[briːð]', 'A2', 'VERB'), 
('To brew', 'Варить;Заваривать', '[bruː]', 'A2', 'VERB'), 
('To celebrate', 'Отмечать', '[ˈsɛlɪbreɪt]', 'A2', 'VERB'), 
('To broadcast', 'Вещать;Транслировать', '[ˈbrɔːdkɑːst]', 'A2', 'VERB'), 
('To modify', 'Изменять;Модифицировать', '[ˈmɒdɪfaɪ]', 'A2', 'VERB'), 
('To bump', 'Ударять', '[bʌmp]', 'A2', 'VERB'), 
('To buzz', 'Жужжать', '[bʌz]', 'A2', 'VERB'), 
('To lead', 'Вести;Лидировать;Быть лидером', '[liːd]', 'A2', 'VERB'), 
('To call back', 'Перезвонить', '[kɔːl bæk]', 'A2', 'VERB'), 
('To waste', 'Тратить впустую;Мусорить', '[weɪst]', 'A2', 'VERB'), 
('To take care', 'Заботиться', '[teɪk keə]', 'A2', 'VERB'), 
('To carry out', 'Выполнять;Осуществлять', '[ˈkæri aʊt]', 'A2', 'VERB'), 
('To carve', 'Вырезать', '[kɑːv]', 'A2', 'VERB'), 
('To cease', 'Прекратить', '[siːs]', 'A2', 'VERB'),
('To collaborate', 'Сотрудничать', '[kəˈlæbəreɪt]', 'A2', 'VERB'), 
('To reward', 'Награждать', '[rɪˈwɔːd]', 'A2', 'VERB'), 
('To come back', 'Возвращаться', '[kʌm bæk]', 'A2', 'VERB'), 
('To relate', 'Относиться;Касаться', '[rɪˈleɪt]', 'A2', 'VERB'), 
('To upgrade', 'Обновлять', '[ʌpˈgreɪd]', 'A2', 'VERB'), 
('To restore', 'Восстановить', '[rɪsˈtɔː]', 'A2', 'VERB'), 
('To describe', 'Описывать', '[dɪsˈkraɪb]', 'A2', 'VERB'), 
('To share', 'Делиться', '[ʃeə]', 'A2', 'VERB'), 
('To increase', 'Увеличивать', '[ˈɪnkriːs]', 'A2', 'VERB'), 
('To automate', 'Автоматизировать', '[ˈɔːtəmeɪt]', 'A2', 'VERB'), 
('To manage', 'Управлять', '[ˈmænɪʤ]', 'A2', 'VERB'), 
('To provide', 'Обеспечивать', '[prəˈvaɪd]', 'A2', 'VERB'), 
('To integrate', 'Соединять;Интегрировать', '[ˈɪntɪgreɪt]', 'A2', 'VERB'), 
('To realize', 'Реализовывать;Осуществлять', '[ˈrɪəlaɪz]', 'A2', 'VERB'), 
('To remind', 'Напоминать', '[ˈrɪmaɪnd]', 'A2', 'VERB'), 
('To install', 'Устанавливать', '[ɪnˈstɔːl]', 'A2', 'VERB'), 
('To download', 'Загружать', '[daʊnˈləʊd]', 'A2', 'VERB'), 
('To unpack', 'Распаковать', '[ʌnˈpæk]', 'A2', 'VERB'), 
('To engage', 'Увлечь;Привлечь', '[ɪnˈgeɪʤ]', 'A2', 'VERB'), 
('To create', 'Создавать', '[kri(ː)ˈeɪt]', 'A2', 'VERB'), 
('To prefer', 'Предпочитать', '[priˈfɜː]', 'A2', 'VERB'), 
('To inspire', 'Вдохновлять', '[ɪnˈspaɪə]', 'A2', 'VERB'), 
('To apply', 'Применять', '[əˈplaɪ]', 'A2', 'VERB'),
('To simplify', 'Упрощать', '[ˈsɪmplɪfaɪ]', 'A2', 'VERB'), 
('To strive', 'Стремиться', '[straɪv]', 'A2', 'VERB'), 
('To arrive', 'Прибывать', '[əˈraɪv]', 'A2', 'VERB'), 
('To enable', 'Разрешить;Включить', '[ɪˈneɪbl]', 'A2', 'VERB'), 
('To support', 'Поддерживать', '[səˈpɔːt]', 'A2', 'VERB'), 
('To allot', 'Выделить', '[əˈlɒt]', 'A2', 'VERB'), 
('To empower', 'Разрешать;Уполномочить', '[ɪmˈpaʊə]', 'A2', 'VERB'), 
('To overwhelm', 'Переполнять', '[əʊvəˈwɛlm]', 'A2', 'VERB'), 
('To fulfill', 'Выполнять', '[fʊlˈfɪl]', 'A2', 'VERB'), 
('To take over', 'Принять на себя', '[teɪk ˈəʊvə]', 'A2', 'VERB'), 
('To encourage', 'Поощрять', '[ɪnˈkʌrɪʤ]', 'A2', 'VERB'), 
('To stimulate', 'Стимулировать', '[ˈstɪmjʊleɪt]', 'A2', 'VERB'), 
('To cause', 'Вызывать', '[kɔːz]', 'A2', 'VERB'), 
('To deal', 'Справляться', '[diːl]', 'A2', 'VERB'), 
('To reach', 'Достигать', '[riːʧ]', 'A2', 'VERB'), 
('To touch', 'Прикасаться', '[tʌʧ]', 'A2', 'VERB'), 
('To attain', 'Достигать;Получать', '[əˈteɪn]', 'A2', 'VERB'), 
('To require', 'Запрашивать;Требовать', '[rɪˈkwaɪə]', 'A2', 'VERB'), 
('To figure out', 'Разбираться', '[ˈfɪgər aʊt]', 'A2', 'VERB'), 
('To forgive', 'Прощать', '[fəˈgɪv]', 'A2', 'VERB'), 
('To light', 'Освещать;Светить', '[laɪt]', 'A2', 'VERB'), 
('To shine', 'Сиять', '[ʃaɪn]', 'A2', 'VERB'), 
('To spread', 'Распространять', '[sprɛd]', 'A2', 'VERB'), 
('To throw', 'Бросать', '[θrəʊ]', 'A2', 'VERB'), 
('To spoil', 'Испортить', '[spɔːɪl]', 'A2', 'VERB'),
('To split', 'Разбить;Разделить', '[splɪt]', 'A2', 'VERB'), 
('To go mad', 'Сходить с ума', '[gəʊ mæd]', 'A2', 'VERB'), 
('To steal', 'Украсть', '[stiːl]', 'A2', 'VERB'), 
('To smell', 'Пахнуть', '[smɛl]', 'A2', 'VERB');

-- существительные NOUN

INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Amount', 'Сумма;Количество', '[əˈmaʊnt]', 'A2', 'NOUN'),
    ('Author', 'Автор', '[ˈɔːθə]', 'A2', 'NOUN'),
    ('Character', 'Характер', '[ˈkærɪktə]', 'A2', 'NOUN'),
    ('Dictionary', 'Словарь', '[ˈdɪkʃ(ə)n(ə)ri]', 'A2', 'NOUN'),
    ('Event', 'Событие', '[ɪˈvɛnt]', 'A2', 'NOUN'),
    ('Guess', 'Предположение;Догадка', '[gɛs]', 'A2', 'NOUN'),
    ('Dashboard', 'Панель управления', '[ˈdæʃbɔːd]', 'A2', 'NOUN'),
    ('Task manager', 'Планировщик задач', '[tɑːsk ˈmænɪʤə]', 'A2', 'NOUN'),
    ('Sick day', 'Больничный', '[sɪk deɪ]', 'A2', 'NOUN'), 
    ('Trouble', 'Проблема', '[ˈtrʌbl]', 'A2', 'NOUN'),
    ('Deadline', 'Дедлайн', '[ˈdɛdlaɪn]', 'A2', 'NOUN'),
    ('Reason', 'Причина;Cмысл', '[ˈriːzn]', 'A2', 'NOUN'),
    ('To-do list', 'Список дел', '[təˈduː lɪst]', 'A2', 'NOUN'),
    ('Remark', 'Замечание;Ремарка', '[ˈrɪˈmɑːk]', 'A2', 'NOUN'),
    ('Proofreading', 'Редактирование;Вычитка', '[ˈpruːfˌriːdɪŋ]', 'A2', 'NOUN'),
    ('Performance', 'Исполнение;Выступление', '[pəˈfɔːməns]', 'A2', 'NOUN'),
    ('Co-working space', 'Ко-воркинг', '[kəʊ-ˈwɜːkɪŋ speɪs]', 'A2', 'NOUN'),
    ('Duty', 'Обязанность', '[ˈdjuːti]', 'A2', 'NOUN'),
    ('Function', 'Функция', '[ˈfʌŋkʃən]', 'A2', 'NOUN'),
    ('Burnout', 'Выгорание', '[ˈbɜːnˈaʊt]', 'A2', 'NOUN'), 
    ('Goal', 'Цель', '[gəʊl]', 'A2', 'NOUN'),
    ('Timetable', 'Расписание', '[ˈtaɪmˌteɪb(ə)l]', 'A2', 'NOUN'),
    ('Area', 'Сфера;Область', '[ˈeərɪə]', 'A2', 'NOUN'),
    ('State', 'Состояние;Положение', '[steɪt]', 'A2', 'NOUN'),
    ('Mentoring', 'Менторство', '[ˈmɛntɔːrɪŋ]', 'A2', 'NOUN'),
    ('Tiredness', 'Усталость', '[ˈtaɪədnəs]', 'A2', 'NOUN'),
    ('Probation period', 'Испытательный срок', '[prəˈbeɪʃən ˈpɪərɪəd]', 'A2', 'NOUN'),
    ('Expectation', 'Ожидание', '[ɛkspɛkˈteɪʃən]', 'A2', 'NOUN'),
    ('Benefit', 'Прибыль', '[ˈbɛnɪfɪt]', 'A2', 'NOUN'),
    ('Salary', 'Зарплата', '[ˈsæləri]', 'A2', 'NOUN'), 
    ('Outsource', 'Аутсорс', '[aʊtˈsɔːs]', 'A2', 'NOUN'),
    ('Team', 'Команда', '[tiːm]', 'A2', 'NOUN'), 
    ('Lead', 'Лидер;Тимлидер', '[liːd]', 'A2', 'NOUN'),
    ('Project', 'Проект', '[ˈprɒʤɛkt]', 'A2', 'NOUN'),  
    ('Check out', 'Проверка', '[ʧɛk aʊt]', 'A2', 'NOUN'),
    ('Research', 'Исследование', '[rɪˈsɜːʧ]', 'A2', 'NOUN'),
    ('Routine', 'Рутина', '[ruːˈtiːn ]', 'A2', 'NOUN'),
    ('Planner', 'Планнер;Блокнот', '[ˈplænə]', 'A2', 'NOUN'), 
    ('Schedule', 'Расписание', '[ˈʃɛdjuːl]', 'A2', 'NOUN'),
    ('Cartoon', 'Мультфильм', '[kɑːˈtuːn]', 'A2', 'NOUN'),
    ('Movie', 'Фильм', '[ˈmuːvi]', 'A2', 'NOUN'),
    ('Circus', 'Цирк', '[ˈsɜːkəs]', 'A2', 'NOUN'),
    ('Composer', 'Композитор', '[kəmˈpəʊzə]', 'A2', 'NOUN'),
    ('Dream', 'Мечта', '[driːm]', 'A2', 'NOUN'),
    ('Daily routine', 'Ежедневная рутина', '[ˈdeɪli ruːˈtiːn]', 'A2', 'NOUN'),
    ('Horror', 'Ужастик', '[ˈhɒrə]', 'A2', 'NOUN'),
    ('Laughter', 'Смех', '[ˈlɑːftə]', 'A2', 'NOUN'),
    ('Novel', 'Роман', '[ˈnɒvəl]', 'A2', 'NOUN'), 
    ('Story', 'История', '[ˈstɔːri]', 'A2', 'NOUN'),
    ('Weather forecast', 'Прогноз погоды', '[ˈwɛðə ˈfɔːkɑːst]', 'A2', 'NOUN'),
  --  ('Thought', 'Мысль' '[θɔːt]', 'A2', 'NOUN'),
    ('Writer', 'Писатель', '[ˈraɪtə]', 'A2', 'NOUN'),
    ('Access', 'Доступ', '[ˈæksɛs]', 'A2', 'NOUN'),
    ('Account', 'Аккаунт', '[əˈkaʊnt]', 'A2', 'NOUN'),
    ('Adventure', 'Приключение', '[ədˈvɛnʧə]', 'A2', 'NOUN'),
    ('Affair', 'Страх', '[əˈfeə]', 'A2', 'NOUN'),
    ('Anniversary', 'Дело;Интрига', '[ænɪˈvɜːsəri]', 'A2', 'NOUN'),
    ('Entertainment', 'Развлечение', '[ɛntəˈteɪnmənt]', 'A2', 'NOUN'),
    ('Amusement', 'Веселье', '[əˈmjuːzmənt]', 'A2', 'NOUN'),
    ('Influence', 'Влияние', '[ˈɪnflʊəns]', 'A2', 'NOUN'),
    ('Attraction', 'Достопримечательность;Аттракцион', '[əˈtrækʃ(ə)n]', 'A2', 'NOUN'),
    ('Rock-climbing', 'Скалолазание', '[rɒk-ˈklaɪmɪŋ]', 'A2', 'NOUN'),
    ('Cycling', 'Катание на велосипеде', '[ˈsaɪklɪŋ]', 'A2', 'NOUN'),
    ('Number painting', 'Живопись по номерам', '[ˈnʌmbə ˈpeɪntɪŋ]', 'A2', 'NOUN'),
    ('Swimming pool', 'Бассейн', '[ˈswɪmɪŋ puːl]', 'A2', 'NOUN'),
    ('Yoga', 'Йога', '[ˈjəʊgə]', 'A2', 'NOUN'),
    ('Coffee shop', 'Кофейня', '[ˈkɒfi ʃɒp]', 'A2', 'NOUN'),
    ('Central park', 'Центральный парк', '[ˈsɛntrəl pɑːk]', 'A2', 'NOUN'),
    ('Inspiration', 'Вдохновение', '[ɪnspəˈreɪʃən]', 'A2', 'NOUN'),
    ('Scenery', 'Пейзаж', '[ˈsiːnəri]', 'A2', 'NOUN'),
    ('Landscape', 'Ландшафт;Пейзаж', '[ˈlænskeɪp]', 'A2', 'NOUN'),
    ('Computer game', 'Компьютерная игра', '[kəmˈpjuːtə geɪm]', 'A2', 'NOUN'),
    ('Mood', 'Настроение', '[muːd]', 'A2', 'NOUN'),
    ('Situation', 'Ситуация', '[sɪtjʊˈeɪʃən]', 'A2', 'NOUN'),
    ('Movement', 'Движение', '[ˈmuːvmənt]', 'A2', 'NOUN'),
    ('Arrangement', 'Договоренность', '[əˈreɪnʤmənt]', 'A2', 'NOUN'),
    ('Accommodation', 'Жилье', '[əˌkɒməˈdeɪʃ(ə)n]', 'A2', 'NOUN'),
    ('Beverage', 'Напиток', '[ˈbɛvərɪʤ]', 'A2', 'NOUN'),
    ('Binge', 'Гулянка', '[bɪnʤ]', 'A2', 'NOUN'),
    ('Activist', 'Активист', '[ˈæktɪvɪst]', 'A2', 'NOUN'),
    ('Pollution', 'Загрязнение', '[pəˈluːʃən]', 'A2', 'NOUN'),
    ('Impurity', 'Примеси;Загрязнение', '[ɪmˈpjʊərɪti]', 'A2', 'NOUN'),
    ('Algae', 'Водоросли', '[ˈælʤiː]', 'A2', 'NOUN'),
    ('Earth', 'Земля', '[ɜːθ]', 'A2', 'NOUN'),
    ('Atmosphere', 'Атмосфера', '[ˈætməsfɪə]', 'A2', 'NOUN'),
    ('Environment', 'Окружающий мир', '[ɪnˈvaɪərənmənt]', 'A2', 'NOUN'),
    ('Climate', 'Климат', '[ˈklaɪmɪt]', 'A2', 'NOUN'),
    ('Air', 'Воздух', '[eə]', 'A2', 'NOUN'),
    ('Water reserve', 'Водные ресурсы', '[ˈwɔːtə rɪˈzɜːv]', 'A2', 'NOUN'),
    ('Greenhouse effect', 'Парниковый эффект', '[ˈgriːnhaʊs ɪˈfɛkt]', 'A2', 'NOUN'),
    ('Oxygen', 'Кислород', '[ˈɒksɪʤən]', 'A2', 'NOUN'),
    ('Explorer', 'Исследователь', '[ɪksˈplɔːrə]', 'A2', 'NOUN'),
    ('Investigation', 'Расследование', '[ɪnˌvɛstɪˈgeɪʃən]', 'A2', 'NOUN'), 
    ('Future', 'Будущее', '[ˈfjuːʧə]', 'A2', 'NOUN'),
    ('Tropic forest', 'Тропический лес', '[ˈtrɒpɪk ˈfɒrɪst]', 'A2', 'NOUN'),
    ('Humidity', 'Влажность;Влага', '[hju(ː)ˈmɪdɪti]', 'A2', 'NOUN'),
    ('Flora', 'Флора', '[ˈflɔːrə]', 'A2', 'NOUN'),
    ('Wildlife', 'Дикая природа;Животные', '[ˈwaɪldlaɪf]', 'A2', 'NOUN'),  
    ('Plastic waste', 'Пластиковые отходы', '[ˈplæstɪk weɪst]', 'A2', 'NOUN'),
    ('Recycling', 'Переработка', '[riːˈsaɪklɪŋ]', 'A2', 'NOUN'),
    ('Hydrosphere', 'Гидросфера', '[ˈhaɪdrəʊsfɪə]', 'A2', 'NOUN'),
    ('Meeting', 'Митинг', '[ˈmiːtɪŋ]', 'A2', 'NOUN'),
    ('Background', 'Происхождение;Фон', '[ˈbækgraʊnd]', 'A2', 'NOUN'),
    ('Bank', 'Берег', '[bæŋk]', 'A2', 'NOUN'),  
    ('Banner', 'Баннер;Реклама', '[ˈbænə]', 'A2', 'NOUN'),
    ('Beast', 'Зверь;Животное', '[biːst]', 'A2', 'NOUN'),
    ('Cave', 'Пещера;Грот', '[keɪv]', 'A2', 'NOUN'),
    ('Caviar', 'Икра', '[ˈkævɪɑː]', 'A2', 'NOUN'),
    ('Charity', 'Благотворительность', '[ˈʧærɪti]', 'A2', 'NOUN'),
    ('Chemistry', 'Химия', '[ˈkɛmɪstri]', 'A2', 'NOUN'),
    ('Economical use', 'Экономное потребление', '[iːkəˈnɒmɪkəl juːz<]', 'A2', 'NOUN'),
    ('Cohesion', 'Уголь', '[kəʊˈhiːʒən]', 'A2', 'NOUN'),  
    ('Commitment', 'Обязательство', '[kəˈmɪtmənt]', 'A2', 'NOUN'),
    ('Concern', 'Озабоченность', '[kənˈsɜːn]', 'A2', 'NOUN'),
    ('Conscience', 'Совесть;Сознание', '[ˈkɒnʃəns]', 'A2', 'NOUN'),
    ('Court', 'Суд', '[kɔːt]', 'A2', 'NOUN'),
    ('Custody', 'Опека;Сохранение', '[ˈkʌstədi]', 'A2', 'NOUN'),
    ('Desert', 'Пустыня', '[ˈdɛzət]', 'A2', 'NOUN'),  
    ('Dimension', 'Разрушение', '[dɪˈmɛnʃən]', 'A2', 'NOUN'),
    ('Disaster', 'Катастрофа', '[dɪˈzɑːstə]', 'A2', 'NOUN'), 
    ('Disease', 'Заболевание', '[dɪˈziːz]', 'A2', 'NOUN'),
    ('Downturn', 'Убыток;Спад', '[ˈdaʊntɜːn]', 'A2', 'NOUN'),
    ('Drain', 'Сток;Слив', '[dreɪn]', 'A2', 'NOUN'),
    ('Emphasis', 'Акцент', '[ˈɛmfəsɪs]', 'A2', 'NOUN'),
    ('Engine', 'Двигатель', '[ˈɛnʤɪn]', 'A2', 'NOUN'),
    ('Evidence', 'Доказательство', '[ˈɛvɪdəns]', 'A2', 'NOUN'), 
    ('Excess', 'Превышение', '[ɪkˈsɛs]', 'A2', 'NOUN'),
    ('Famine', 'Голод', '[ˈfæmɪn]', 'A2', 'NOUN'),
    ('Detriment', 'Ущерб', '[ˈdɛtrɪmənt]', 'A2', 'NOUN');

-- adjectives прилагательные

INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Blind', 'Слепой', '[blaɪnd]', 'A2', 'ADJECTIVE'),
    ('Catchy', 'Броский;Запоминающийся', '[ˈkæʧi]', 'A2', 'ADJECTIVE'),
    ('Common', 'Распространенный', '[ˈkɒmən]', 'A2', 'ADJECTIVE'),
    ('Familiar', 'Знакомый', '[fəˈmɪliə]', 'A2', 'ADJECTIVE'),
    ('Frequent', 'Частый', '[ˈfriːkwənt]', 'A2', 'ADJECTIVE'),
    ('Recurrent', 'Повторяющийся', '[rɪˈkʌrənt]', 'A2', 'ADJECTIVE'),
    ('Enormous', 'Огромный', '[ɪˈnɔːməs]', 'A2', 'ADJECTIVE'),
    ('Expensive', 'Дорогой', '[ɪksˈpɛnsɪv]', 'A2', 'ADJECTIVE'),
    ('Valuable', 'Ценный', '[ˈvæljʊəbl]', 'A2', 'ADJECTIVE'),
    ('Muslim', 'Мусульманский', '[ˈmʊslɪm]', 'A2', 'ADJECTIVE'),
    ('Lucky', 'Удачный', '[ˈlʌki]', 'A2', 'ADJECTIVE'),
    ('Clear', 'Чистый;Понятный', '[klɪə]', 'A2', 'ADJECTIVE'),
    ('Scientific', 'Научный', '[saɪənˈtɪfɪk]', 'A2', 'ADJECTIVE'),
    ('Huge', 'Большой;Огромный', '[hjuːʤ]', 'A2', 'ADJECTIVE'),
    ('Messy', 'Беспорядочный', '[ˈmɛsi]', 'A2', 'ADJECTIVE'),
    ('Unforgettable', 'Незабываемый','[ʌnfəˈgɛtəbl]', 'A2', 'ADJECTIVE'),
    ('False', 'Неверный;Неправильный', '[fɔːls]', 'A2', 'ADJECTIVE'),
    ('Fierce', 'Свирепый;Жестокий', '[fɪəs]', 'A2', 'ADJECTIVE'),
    ('Explicit', 'Ярко выраженный', '[ɪksˈplɪsɪt]', 'A2', 'ADJECTIVE'),
    ('Exterior', 'Внешний', '[ɛksˈtɪərɪə]', 'A2', 'ADJECTIVE'),
    ('Hidden', 'Скрытый', '[ˈhɪdn]', 'A2', 'ADJECTIVE'),
    ('Powerful', 'Мощный', '[ˈpaʊəfʊl]', 'A2', 'ADJECTIVE'),
    ('Internal', 'Внутренний', '[ɪnˈtɜːnl]', 'A2', 'ADJECTIVE'), 
    ('Fabulous', 'Невероятный', '[ˈfæbjʊləs]', 'A2', 'ADJECTIVE'),
    ('Beautiful', 'Красивый', '[ˈbjuːtəfʊl]', 'A2', 'ADJECTIVE'),
    ('Gorgeous', 'Великолепный', '[ˈgɔːʤəs]', 'A2', 'ADJECTIVE'),
    ('Fruitful', 'Плодотворный', '[ˈfruːtfʊl]', 'A2', 'ADJECTIVE'),
    ('Formidable', 'Замечательный', '[ˈfɔːmɪdəbl]', 'A2', 'ADJECTIVE'), 
    ('Fortunate', 'Удачливый;Счастливый', '[ˈfɔːʧnɪt]', 'A2', 'ADJECTIVE'),
    ('Frail', 'Хилый;Хрупкий', '[freɪl]', 'A2', 'ADJECTIVE'),
    ('Friendly', 'Дружелюбный', '[ˈfrɛndli]', 'A2', 'ADJECTIVE'),
    ('Loyal', 'Лояльный', '[ˈlɔɪəl]', 'A2', 'ADJECTIVE'),
    ('General', 'Общий;Генеральный', '[ˈʤɛnərəl]', 'A2', 'ADJECTIVE'),
    ('Generous', 'Щедрый', '[ˈʤɛnərəs]', 'A2', 'ADJECTIVE'),
    ('Gradual', 'Постепенный', '[ˈgrædjʊəl]', 'A2', 'ADJECTIVE'),
    ('Productive', 'Продуктивный', '[prəˈdʌktɪv]', 'A2', 'ADJECTIVE'),
    ('Protected', 'Защищенный', '[prəˈtɛktɪd]', 'A2', 'ADJECTIVE'),
    ('Hardy', 'Выносливый', '[ˈhɑːdi]', 'A2', 'ADJECTIVE'),
    ('Peaceful', 'Мирный;Миролюбивый', '[ˈpiːsfʊl]', 'A2', 'ADJECTIVE'),
    ('Digital', 'Цифровой', '[ˈdɪʤɪtl]', 'A2', 'ADJECTIVE'),
    ('Social', 'Социальный', '[ˈsəʊʃəl]', 'A2', 'ADJECTIVE'),
    ('Hideous', 'Отвратительный', '[hɪdɪə]', 'A2', 'ADJECTIVE'),
    ('Awful', 'Ужасный', '[ˈɔːfʊl]', 'A2', 'ADJECTIVE'), 
    ('Awesome', 'Милый', '[ˈɔːsəm]', 'A2', 'ADJECTIVE'), 
    ('High-quality', 'Высококачественный', '[haɪ-ˈkwɒlɪti]', 'A2', 'ADJECTIVE'),
    ('Helpless', 'Беспомощный', '[ˈhɛlplɪs]', 'A2', 'ADJECTIVE'),
    ('Hilarious', 'Уморительный','[ hɪˈleərɪəs]', 'A2', 'ADJECTIVE'),
    ('Idle', 'Безработный', '[ˈaɪdl]', 'A2', 'ADJECTIVE'),
    ('Immediate', 'Незамедлительный', '[ɪˈmiːdiət]', 'A2', 'ADJECTIVE'),
    ('Main', 'Главный', '[meɪn]', 'A2', 'ADJECTIVE'),
    ('European', 'Европейский', '[jʊərəˈpi(ː)ən]', 'A2', 'ADJECTIVE'),
    ('Simultaneous', 'Одновременный', '[sɪməlˈteɪniəs]', 'A2', 'ADJECTIVE'), 
    ('Special', 'Специальный', '[ˈspɛʃəl]', 'A2', 'ADJECTIVE'),
    ('Visible', 'Видимый', '[ˈvɪzəbl]', 'A2', 'ADJECTIVE'),  
    ('Honest', 'Честный', '[ˈɒnɪst]', 'A2', 'ADJECTIVE'),
    ('Mortal', 'Смертельный', '[ˈmɔːtl]', 'A2', 'ADJECTIVE'),
    ('Hyperactive', 'Гиперактивный', '[ˈhaɪpə ˈæktɪv]', 'A2', 'ADJECTIVE'), 
    ('Personal', 'Личный;Персональный', '[ˈpɜːsnl]', 'A2', 'ADJECTIVE'),
    ('Foolish', 'Безумный;Глупый', '[ˈfuːlɪʃ]', 'A2', 'ADJECTIVE'),
    ('Sudden', 'Внезапный', '[ˈsʌdn]', 'A2', 'ADJECTIVE');


-- наречия adverbs

INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Endlessly', 'Бесконечно', '[ˈɛndlɪsli]', 'A2', 'ADVERB'),
    ('Unselfishly', 'Бескорыстно', '[ʌnˈsɛlfɪʃli]', 'A2', 'ADVERB'),
    ('Generously', 'Щедро', '[ˈʤɛnərəsli]', 'A2', 'ADVERB'), 
    ('Along', 'Вдоль;По', '[əˈlɒŋ]', 'A2', 'ADVERB'),
    ('Accordingly', 'Соответственно', '[əˈkɔːdɪŋli]', 'A2', 'ADVERB'),
    ('Subsequently', 'Впоследствии', '[ˈsʌbsɪkwəntli]', 'A2', 'ADVERB'),
    ('Subtly', 'Тонко', '[ˈsʌtli]', 'A2', 'ADVERB'),
    ('Precisely', 'Точно;Четко', '[prɪˈsaɪsli]', 'A2', 'ADVERB'),
    ('Better', 'Лучше', '[ˈbɛtə]', 'A2', 'ADVERB'), 
    ('Everywhere', 'Везде;Где угодно', '[ˈɛvrɪweə]', 'A2', 'ADVERB'),
    ('Out', 'За;Из', '[aʊt]', 'A2', 'ADVERB'),
    ('Fully', 'Полностью', '[ˈfʊli]', 'A2', 'ADVERB'),
    ('Partly', 'Частично', '[ˈpɑːtli]', 'A2', 'ADVERB'),
    ('Utterly', 'Полностью', '[ˈʌtəli]', 'A2', 'ADVERB'),
    ('Entirely', 'Совершенно;Целиком', '[ɪnˈtaɪəli]', 'A2', 'ADVERB'),
    ('Therefore', 'Поэтому', '[ˈðeəfɔː]', 'A2', 'ADVERB'),
    ('Hence', 'Вот почему;Отсюда', '[hɛns]', 'A2', 'ADVERB'),
    ('Consequently', 'Таким образом;Соответственно', '[ˈkɒnsɪkwəntli]', 'A2', 'ADVERB'),
    ('Bravely', 'Отважно;Храбро', '[ˈbreɪvli]', 'A2', 'ADVERB'),
    ('Carefully', 'Внимательно;Осторожно', '[ˈkeəfli]', 'A2', 'ADVERB'),
    ('Seldom', 'Редко', '[ˈsɛldəm]', 'A2', 'ADVERB'), 
    ('Frequently', 'Часто', '[ˈfriːkwəntli]', 'A2', 'ADVERB'),
    ('Outside', 'Снаружи', '[aʊtˈsaɪd]', 'A2', 'ADVERB'),
    ('Upstairs', 'Наверху', '[ʌpˈsteəz]', 'A2', 'ADVERB'),
    ('Downstairs', 'Внизу', '[daʊnˈsteəz]', 'A2', 'ADVERB'),
    ('Quite', 'Вполне', '[kwaɪt]', 'A2', 'ADVERB'),
    ('Early', 'Рано', '[ˈɜːli]', 'A2', 'ADVERB'),
    ('Simply', 'Легко, просто', '[ˈsɪmpli]', 'A2', 'ADVERB'), 
    ('Hard', 'Трудно', '[hɑːd]', 'A2', 'ADVERB'),
    ('Late', 'Поздно', '[leɪt]', 'A2', 'ADVERB');


