
-- VERB глагол
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('To abolish', 'Отменять;Уничтожать;Упразднять', '[əˈbɒlɪʃ]', 'B1', 'VERB'),
    ('To approve', 'Утвердить;Одобрить', '[əˈpruːv]', 'B1', 'VERB'),
    ('To boast', 'Гордиться;Хвастаться', '[bəʊst]', 'B1', 'VERB'),
    ('To contribute', 'Жертвовать;Вносить свой вклад', '[kənˈtrɪbju(ː)t]', 'B1', 'VERB'),
    ('To deliver', 'Доставлять;Поставлять;Приносить', '[dɪˈlɪvə]', 'B1', 'VERB'),
    ('To descend', 'Спуститься;Сходить;Снизойти', '[dɪˈsɛnd]', 'B1', 'VERB'),
    ('To concentrate', 'Сосредотачиваться', '[ˈkɒnsəntreɪt]', 'B1', 'VERB'), 
    ('To distract', 'Отвлечь;Отвлекать', '[dɪsˈtrækt]', 'B1', 'VERB'),
    ('To torture', 'Мучить;Терзать', '[ˈtɔːʧə]', 'B1', 'VERB'),
    ('To confuse', 'Путать;Запутать;Сбить с толку', '[kənˈfjuːz]', 'B1', 'VERB'),
    ('To abandon', 'Покинуть;Бросить;Оставить', '[əˈbændən]', 'B1', 'VERB'),
    ('To escape', 'Совершить побег;Убежать;Сбежать', '[ɪsˈkeɪp]', 'B1', 'VERB'),
    ('To distribute', 'Распространять;Распределить', '[dɪsˈtrɪbju(ː)t]', 'B1', 'VERB'),
    ('To elaborate', 'Разрабатывать;Прорабатывать', '[ɪˈlæbərɪt]', 'B1', 'VERB'),
    ('To construct', 'Строить;Построить', '[kənˈstrʌkt]', 'B1', 'VERB'),
    ('To humiliate', 'Унижать', '[hju(ː)ˈmɪlɪeɪt]', 'B1', 'VERB'),
    ('To maintain', 'Поддерживать', '[meɪnˈteɪn]', 'B1', 'VERB'),
    ('To squeeze', 'Сжимать;Выжимать;Сжать', '[skwiːz]', 'B1', 'VERB'),
    ('To delegate', 'Делегировать;Посылать', '[ˈdɛlɪgɪt]', 'B1', 'VERB'),
    ('To transfer', 'Передавать;Перечислять', '[ˈtrænsfə(ː)]', 'B1', 'VERB'),
    ('To employ', 'Нанимать;Использовать;Работать', '[ɪmˈplɔɪ]', 'B1', 'VERB'),
    ('To catch', 'Поймать;Ловить', '[kæʧ]', 'B1', 'VERB'),
    ('To commit', 'Совершить;Зафиксировать;Поручить', '[kəˈmɪt]', 'B1', 'VERB'),
    ('To arrange', 'Организовать, Устроить', '[əˈreɪnʤ]', 'B1', 'VERB'), 
    ('To implement', 'Внедрить;Реализовать;Осуществить', '[ˈɪmplɪmənt]', 'B1', 'VERB'),
    ('To insulate', 'Ограждать', '[ˈɪnsjʊleɪt]', 'B1', 'VERB'),
    ('To encourage', 'Стимулировать', '[ɪnˈkʌrɪʤ]', 'B1', 'VERB'),
    ('To foster', 'Поощрять', '[ˈfɒstə]', 'B1', 'VERB'),
    ('To boost', 'Повышать', '[buːst]', 'B1', 'VERB'),
    ('To optimize', 'Оптимизировать', '[ˈɒptɪmaɪz]', 'B1', 'VERB'),
    ('To rank', 'Ранжировать', '[ræŋk]', 'B1', 'VERB'),
    ('To identify', 'Определить;Идентифицировать', '[aɪˈdɛntɪfaɪ]', 'B1', 'VERB'), 
    ('To empower', 'Наделить полномочиями;Расширять', '[ɪmˈpaʊə]', 'B1', 'VERB'),
    ('To ensure', 'Обеспечить;Убедить;Гарантировать', '[ɪnˈʃʊə]', 'B1', 'VERB'),
    ('To accomplish', 'Выполнить;Завершить;Осуществить', '[əˈkɒmplɪʃ]', 'B1', 'VERB'),
    ('To customize', 'Настроить;Сделать', '[ˈkʌstəˌmaɪz]', 'B1', 'VERB'),
    ('To localize', 'Локализовать;Определить', '[ˈləʊkəlaɪz]', 'B1', 'VERB'), 
    ('To tailor', 'Приспособить', '[ˈteɪlə]', 'B1', 'VERB'),
    ('To validate', 'Удостоверять', '[ˈvælɪdeɪt]', 'B1', 'VERB'), 
    ('To reserve', 'Резервировать', '[rɪˈzɜːv]', 'B1', 'VERB'),
    ('To estimate', 'Оценивать', '[ˈɛstɪmɪt]', 'B1', 'VERB'),
    ('To consulate', 'Консультировать', '[ˈkɒnsjʊlɪt]', 'B1', 'VERB'),
    ('To regard', 'Рассматривать;Учитывать;Относиться', '[rɪˈgɑːd]', 'B1', 'VERB'),
    ('To indicate', 'Указывать;Обозначать;Показывать', '[ˈɪndɪkeɪt]', 'B1', 'VERB'),
    ('To unify', 'Объединять', '[juːnɪfaɪ]', 'B1', 'VERB'),
    ('To digitalize', 'Оцифровать;Перевести в online-формат', '[ˈdɪdʒɪtəlaɪz]', 'B1', 'VERB'),
    ('To expose', 'Подвергать', '[ɪksˈpəʊz]', 'B1', 'VERB'), 
    ('To idealize', 'Идеализировать','[ aɪˈdɪəlaɪz]', 'B1', 'VERB'),
    ('To navigate', 'Ориентироваться', '[ˈnævɪgeɪt]', 'B1', 'VERB'),
    ('To sustain', 'Выдерживать', '[səsˈteɪn]', 'B1', 'VERB'), 
    ('To constrain', 'Сдерживать', '[kənˈstreɪn]', 'B1', 'VERB'),
    ('To evade', 'Обойти', '[ɪˈveɪd]', 'B1', 'VERB'),
    ('To purchase', 'Приобретать', '[ˈpɜːʧəs]', 'B1', 'VERB'),
    ('To earn', 'Зарабатывать', '[ɜːn]', 'B1', 'VERB'), 
    ('To make sure', 'Убедиться', '[meɪk ʃʊə]', 'B1', 'VERB'),
    ('To prototype', 'Создать прототип;План', '[ˈprəʊtəʊtaɪp]', 'B1', 'VERB'),
    ('To endeavour', 'Стремиться', '[ɪnˈdɛvə]', 'B1', 'VERB'),
    ('To blend', 'Смешивать', '[blɛnd]', 'B1', 'VERB'),
    ('To prioritize', 'Расставить приоритеты', '[praɪˈɒrɪˌtaɪz]', 'B1', 'VERB'), 
    ('To mitigate', 'Смягчать;Принимать', '[ˈmɪtɪgeɪt]', 'B1', 'VERB'),
    ('To emphasize', 'Подчеркнуть;Придать акцент', '[ˈɛmfəsaɪz]', 'B1', 'VERB'),
    ('To observe', 'Наблюдать;Замечать', '[əbˈzɜːv]', 'B1', 'VERB'),
    ('To evolve', 'Развиваться;Расти;Проявляться', '[ ɪˈvɒlv]', 'B1', 'VERB'), 
    ('To incentivize', 'Стимулировать;Побуждать', '[ɪnˈsen.tɪ.vaɪz]', 'B1', 'VERB'),
    ('To respond', 'Реагировать, Отвечать', '[rɪsˈpɒnd]', 'B1', 'VERB'),
    ('To connect', 'Соединить', '[kəˈnɛkt]', 'B1', 'VERB'),  
    ('To command', 'Командовать', '[kəˈmɑːnd]', 'B1', 'VERB'),
    ('To check-out', 'Проверить;Оформить', '[ʧɛk-aʊt]', 'B1', 'VERB'),
    ('To extend', 'Продлить;Расширить;Увеличить', '[ɪksˈtɛnd]', 'B1', 'VERB'),
    ('To retain', 'Оставить;Удержать;Сохранить', '[rɪˈteɪn]', 'B1', 'VERB'),
    ('To exhibit', 'Показывать', '[ɪgˈzɪbɪt]', 'B1', 'VERB'), 
    ('To invent', 'Изобретать', '[ɪnˈvɛnt]', 'B1', 'VERB'),
    ('To abridge', 'Ограничивать', '[əˈbrɪʤ]', 'B1', 'VERB'),
    ('To self-express', 'Самовыражаться', '[sɛlf-ɪksˈprɛs]', 'B1', 'VERB'), 
    ('To neglect', 'Пренебрегать', '[nɪˈglɛkt]', 'B1', 'VERB'), 
    ('To negotiate', 'Договариваться;Вести переговоры','[nɪˈgəʊʃɪeɪt]', 'B1', 'VERB'),
    ('To upgrade', 'Повышать;Улучшать', '[ʌpˈgreɪd]', 'B1', 'VERB'), 
    ('To renew', 'Обновить', '[rɪˈnjuː]', 'B1', 'VERB'),
    ('To specialize', 'Специализироваться', '[ˈspɛʃəlaɪz]', 'B1', 'VERB'),
    ('To balance', 'Уравновешивать', '[ˈbæləns]', 'B1', 'VERB'),
    ('To absorb', 'Поглощать', '[əbˈsɔːb]', 'B1', 'VERB'),
    ('To overwhelm', 'Переполнять', '[əʊvəˈwɛlm]', 'B1', 'VERB'), 
    ('To align', 'Выравнивать', '[əˈlaɪn]', 'B1', 'VERB'), 
    ('To withdraw', 'Отстраниться', '[wɪðˈdrɔː]', 'B1', 'VERB'), 
    ('To whistle', 'Свистеть', '[ˈwɪsl]', 'B1', 'VERB'),
    ('To suspect', 'Подозревать', '[ˈsʌspɛkt]', 'B1', 'VERB'), 
    ('To surrender', 'Сдаваться', '[səˈrɛndə]', 'B1', 'VERB'),
    ('To depend on', 'Зависеть от', '[dɪˈpɛnd ɒn]', 'B1', 'VERB'),  
    ('To correct', 'Исправлять', '[kəˈrɛkt]', 'B1', 'VERB'), 
    ('To define', 'Определить', '[dɪˈfaɪn]', 'B1', 'VERB'),
    ('To visualize', 'Визуализировать', '[ˈvɪzjʊəlaɪz]', 'B1', 'VERB'),
    ('To design', 'Проектировать', '[dɪˈzaɪn]', 'B1', 'VERB'), 
    ('To minimize', 'Минимизировать', '[ˈmɪnɪmaɪz]', 'B1', 'VERB'),
    ('To disturb', 'Нарушить;Беспокоить', '[dɪsˈtɜːb]', 'B1', 'VERB'), 
    ('To integrate', 'Интегрировать', '[ˈɪntɪgreɪt]', 'B1', 'VERB'),
    ('To exchange', 'Обменивать;Менять', '[ɪksˈʧeɪnʤ]', 'B1', 'VERB'),  
    ('To organize', 'Организовать', '[ˈɔːgənaɪz]', 'B1', 'VERB'),
    ('To collaborate', 'Сотрудничать', '[kəˈlæbəreɪt]', 'B1', 'VERB'),
    ('To embed', 'Встраивать', '[ɪmˈbɛd]', 'B1', 'VERB'),
    ('To generate', 'Генерировать', '[ˈʤɛnəreɪt]', 'B1', 'VERB');

-- NOUN существительное

INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Kindness', 'Доброта', '[ˈkaɪndnɪs]', 'B1', 'NOUN'),
    ('Justice', 'Справедливость', '[ˈʤʌstɪs]', 'B1', 'NOUN'),
    ('Disgust', 'Отвращение;Брезгливость', '[dɪsˈgʌst]', 'B1', 'NOUN'),
    ('Suggestion', 'Предложение;Суждение;Идея', '[səˈʤɛsʧən]', 'B1', 'NOUN'),
    ('Nobility', 'Благородство;Достоинство', '[nəʊˈbɪlɪti]', 'B1', 'NOUN'),
    ('Commotion', 'Суета', '[kəˈməʊʃən]', 'B1', 'NOUN'),
    ('Adherence', 'Приверженность', '[ədˈhɪərəns]', 'B1', 'NOUN'),
    ('Devotion', 'Преданность', '[dɪˈvəʊʃən]', 'B1', 'NOUN'),
    ('Enticement', 'Приманка;Соблазн;Заманивание', '[ɪnˈtaɪsmənt]', 'B1', 'NOUN'),
    ('Attractiveness', 'Привлекательность', '[əˈtræktɪvnəs]', 'B1', 'NOUN'),
    ('Freedom-loving', 'Свободолюбие', '[ˈfriːdəm-ˈlʌvɪŋ]', 'B1', 'NOUN'),
    ('Rebel', 'Бунтарь', '[ˈrɛbl]', 'B1', 'NOUN'),
    ('Influence', 'Влияние', '[ˈɪnflʊəns]', 'B1', 'NOUN'),
    ('Sway', 'Колебание', '[sweɪ]', 'B1', 'NOUN'),
    ('Willpower', 'Сила воли', '[ˈwɪlˌpaʊə]', 'B1', 'NOUN'),
    ('Inequality', 'Неравенство', '[ˌɪni(ː)ˈkwɒlɪti]', 'B1', 'NOUN'),
    ('Violence', 'Насилие;Жестокость', '[ˈvaɪələns]', 'B1', 'NOUN'),
    ('Bullying', 'Издевательство;Травля', '[ˈbʊliɪŋ]', 'B1', 'NOUN'),
    ('Godliness', 'Благочестие;Бодрость', '[ˈgɒdlɪnɪs]', 'B1', 'NOUN'),
    ('Compassion', 'Сострадание', '[kəmˈpæʃən]', 'B1', 'NOUN'),
    ('Inclusivity', 'Инклюзивность', '[ɪnˌkluːˈsɪvətɪ]', 'B1', 'NOUN'),
    ('Reciprocity', 'Взаимность;Обоюдность', '[rɛsɪˈprɒsɪti]', 'B1', 'NOUN'),
    ('Friskiness', 'Игривость;Раскованность;Живость', '[ˈfrɪskɪnəs]', 'B1', 'NOUN'),
    ('Fervor', 'Пылкость;Задор;Рвение', '[ˈfɜːvə]', 'B1', 'NOUN'),
    ('Youth', 'Молодежь;Юноша;Молодость', '[juːθ]', 'B1', 'NOUN'),
    ('Adolescence', 'Подростковый возраст;Отрочество', '[ædəʊˈlɛsns]', 'B1', 'NOUN'),
    ('Prerequisite', 'Предпосылка;Условие', '[ˌpriːˈrɛkwɪzɪt]', 'B1', 'NOUN'),
    ('Fortune', 'Судьба;Удача;Желание;Успех', '[ˈfɔːʧən]', 'B1', 'NOUN'),
    ('Stubbornness', 'Упрямость', '[ˈstʌbənnɪs]', 'B1', 'NOUN'),
    ('Disappointment', 'Разочарование', '[dɪsəˈpɔɪntmənt]', 'B1', 'NOUN'),
    ('Distancing', 'Дистанцирование', '[ˈdɪstənsɪŋ]', 'B1', 'NOUN'),
    ('Isolation', 'Изоляция', '[ˌaɪsəʊˈleɪʃən]', 'B1', 'NOUN'),
    ('Self-care', 'Забота о себе', '[sɛlf-keə]', 'B1', 'NOUN'),
    ('Medication', 'Лекарство', '[ˌmɛdɪˈkeɪʃən]', 'B1', 'NOUN'),
    ('Celebration', 'Мероприятие', '[ˌsɛlɪˈbreɪʃən]', 'B1', 'NOUN'),
    ('Physician', 'Врач;Доктор;Терапевт', '[fɪˈzɪʃən]', 'B1', 'NOUN'),
    ('Treatment', 'Лечение', '[ˈtriːtmənt]', 'B1', 'NOUN'),
    ('Improvement', 'Улучшение', '[ɪmˈpruːvmənt]', 'B1', 'NOUN'),
    ('Symptom', 'Симптом', '[ˈsɪmptəm]', 'B1', 'NOUN'),
    ('Dismay', 'Огорчение', '[dɪsˈmeɪ]', 'B1', 'NOUN'),
    ('Cancellation', 'Отмена', '[ˌkænsəˈleɪʃən]', 'B1', 'NOUN'),
    ('Suspiciousness', 'Подозрительность', '[səsˈpɪʃəsnəs]', 'B1', 'NOUN'),
    ('Escalation', 'Обострение;Эскалация', '[ˌɛskəˈleɪʃən]', 'B1', 'NOUN'),
    ('Proceeding', 'Разбирательство', '[prəˈsiːdɪŋ]', 'B1', 'NOUN'),
    ('Awareness', 'Осознание', '[əˈweənəs]', 'B1', 'NOUN'),
    ('Responsibility', 'Ответственность', '[rɪsˌpɒnsəˈbɪlɪti]', 'B1', 'NOUN'),
    ('Aftermath', 'Последствие', '[ˈɑːftəmæθ]', 'B1', 'NOUN'),
    ('Weakness', 'Слабость', '[ˈwiːknɪs]', 'B1', 'NOUN'),
    ('Rivalry', 'Соперничество;Противостояние', '[raɪvəlri]', 'B1', 'NOUN'),
    ('Restlessness', 'Беспокойство', '[ˈrɛstlɪsnɪs]', 'B1', 'NOUN'),
    ('Uncertainty', 'Неуверенность;Неопределенность', '[ʌnˈsɜːtnti]', 'B1', 'NOUN'),
    ('Stress resistance', 'Стрессоустойчивость', '[strɛs rɪˈzɪstəns]', 'B1', 'NOUN'),
    ('Conscience', 'Совесть', '[kɒnʃəns]', 'B1', 'NOUN'),
    ('Mindfulness', 'Внимательность;Мышление;Осознанность', '[ˈmaɪndfʊlnəs]', 'B1', 'NOUN'),
    ('Protection', 'Защита;Протекция', '[prəˈtɛkʃən]', 'B1', 'NOUN'),
    ('Referral', 'Направление', '[rɪˈfɜrəl]', 'B1', 'NOUN'),
    ('Hopelessness', 'Безнадежность', '[ˈhəʊplɪsnɪs]', 'B1', 'NOUN'),
    ('Reliability', 'Надежность', '[rɪˌlaɪəˈbɪlɪti]', 'B1', 'NOUN'),
    ('Verification', 'Проверка', '[ˌvɛrɪfɪˈkeɪʃən]', 'B1', 'NOUN'),
    ('Self-isolation', 'Самоизоляция', '[sɛlf-ˌaɪsəʊˈleɪʃən]', 'B1', 'NOUN'),
    ('Provocation', 'Провокация', '[prɒvəˈkeɪʃən]', 'B1', 'NOUN'),
    ('Prevention', 'Профилактика', '[prɪˈvɛnʃən]', 'B1', 'NOUN'),
    ('Side effect', 'Побочный эффект', '[saɪd ɪˈfɛkt]', 'B1', 'NOUN'),
    ('Vaccination', 'Вакцинация', '[ˌvæksɪˈneɪʃən]', 'B1', 'NOUN'),
    ('Immunization', 'Иммунизация', '[ɪˌmju(ː)naɪˈzeɪʃən]', 'B1', 'NOUN'),
    ('Contradiction', 'Противоречие', '[ˌkɒntrəˈdɪkʃən]', 'B1', 'NOUN'),
    ('Emotion', 'Эмоция', '[ɪˈməʊʃən]', 'B1', 'NOUN'),
    ('Disagreement', 'Разногласие', '[ˌdɪsəˈgriːmənt]', 'B1', 'NOUN'),
    ('Misunderstanding', 'Недоразумение;Недопонимание', '[ˌmɪsʌndəˈstændɪŋ]', 'B1', 'NOUN'),
    ('Negotiation', 'Переговоры', '[nɪˌgəʊʃɪˈeɪʃən]', 'B1', 'NOUN'),
    ('Downfall', 'Падение;Упадок;Крах;Понижение', '[ˈdaʊnfɔːl]', 'B1', 'NOUN'),
    ('Setback', 'Неудача;Провал', '[ˈsɛtbæk]', 'B1', 'NOUN'),
    ('Bad luck', 'Невезение;Несчастье', '[bæd lʌk]', 'B1', 'NOUN'),
    ('Depression', 'Депрессия', '[dɪˈprɛʃən]', 'B1', 'NOUN'),
    ('Solitude', 'Одиночество', '[ˈsɒlɪtjuːd]', 'B1', 'NOUN'),
    ('Self-blame', 'Самобичевание', '[sɛlf-bleɪm]', 'B1', 'NOUN'),
    ('Disorder', 'Расстройство;Разлад', '[dɪsˈɔːdə]', 'B1', 'NOUN'),
    ('Instability', 'Нестабильность', '[ɪnstəˈbɪlɪti]', 'B1', 'NOUN'),
    ('Challenge', 'Вызов;Сложность', '[ˈʧælɪnʤ]', 'B1', 'NOUN'),
    ('Sustainability', 'Устойчивость;Жизнеспособность', '[səsˌteɪnəˈbɪlɪti]', 'B1', 'NOUN'),
    ('Duration', 'Продолжительность', '[djʊəˈreɪʃən]', 'B1', 'NOUN'),
    ('Luckiness', 'Удачливость;Везение', '[ˈlʌkɪnəs]', 'B1', 'NOUN'),
    ('Fluke', 'Случайность;Шанс', '[fluːk]', 'B1', 'NOUN'),
    ('Winning', 'Выигрыш;Победа;Завоевание', '[ˈwɪnɪŋ]', 'B1', 'NOUN'),
    ('Lottery', 'Лотерея', '[ˈlɒtəri]', 'B1', 'NOUN'),
    ('Destination', 'Предназначение', '[ˌdɛstɪˈneɪʃən]', 'B1', 'NOUN'),
    ('Advantage', 'Преимущество', '[ədˈvɑːntɪʤ]', 'B1', 'NOUN'),
    ('Win-win', 'Победа;Выигрыш', '[wɪn-wɪn]', 'B1', 'NOUN'),
    ('Condition', 'Условие;Обстоятельство;Состояние', '[kənˈdɪʃən]', 'B1', 'NOUN'),
    ('Contest', 'Соревнование;Борьба;Конкурс', '[ˈkɒntɛst]', 'B1', 'NOUN'),
    ('Humbleness', 'Смирение;Скромность;Покорность', '[ˈhʌmblnəs]', 'B1', 'NOUN'),
    ('Fearlessness', 'Бесстрашие', '[ˈfɪəlɪsnəs]', 'B1', 'NOUN'),
    ('Hardening', 'Закалка;Твердость', '[ˈhɑːdnɪŋ]', 'B1', 'NOUN'),
    ('Buoyancy', 'Оживленность;Жизнелюбие', '[ˈbɔɪənsi]', 'B1', 'NOUN'),
    ('Cheerfulness', 'Жизнерадостность;Веселость', '[ˈʧɪəfʊlnəs]', 'B1', 'NOUN'),
    ('Hospitality', 'Гостеприимство;Радушие', '[hɒspɪˈtælɪti]', 'B1', 'NOUN'),
    ('Pessimism', 'Пессимизм', '[ˈpɛsɪmɪzm]', 'B1', 'NOUN'),
    ('Morale', 'Мораль;Дух;Нрав;Мужество', '[mɒˈrɑːl]', 'B1', 'NOUN'),
    ('Wisdom', 'Мудрость', '[ˈwɪzdəm]', 'B1', 'NOUN'),
    ('Proficiency', 'Мастерство;Умение;Квалификация', '[prəˈfɪʃənsi]', 'B1', 'NOUN'),
    ('Applicant', 'Претендент;Соискатель;Заявитель', '[ˈæplɪkənt]', 'B1', 'NOUN'),
    ('Decisiveness', 'Решительность', '[dɪˈsaɪsɪvnəs]', 'B1', 'NOUN'),
    ('Loophole', 'Лазейка;Дыра', '[ˈluːphəʊl]', 'B1', 'NOUN'),
    ('Frustration', 'Фрустрация;Разочарование', '[frʌsˈtreɪ.ʃən]', 'B1', 'NOUN'),
    ('Knowledge', 'Знание;Познание', '[ˈnɒlɪʤ]', 'B1', 'NOUN'),
    ('Decision-making', 'Принятие решения', '[dɪˈsɪʒən-ˈmeɪkɪŋ]', 'B1', 'NOUN'),
    ('Alacrity', 'Аккуратность;Активность;Стремительность', '[əˈlækrɪti]', 'B1', 'NOUN'),
    ('Extremity', 'Крайность;Упорство;Чрезмерность', '[ɪksˈtrɛmɪti]', 'B1', 'NOUN'),
    ('Background', 'Фон;Предпосылка', '[ˈbækgraʊnd]', 'B1', 'NOUN'),
    ('Preparatory', 'Подготовка', '[prɪˈpærətəri]', 'B1', 'NOUN');


-- Adjective прилагательное

INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Arrogant', 'Высокомерный;Заносчивый', '[ˈærəʊgənt]', 'B1', 'ADJECTIVE'),
    ('Civilian', 'Гражданский', '[səˈvɪljən]', 'B1', 'ADJECTIVE'),
    ('Commercial', 'Коммерческий', '[kəˈmɜːʃəl]', 'B1', 'ADJECTIVE'),
    ('Convenient', 'Удобный', '[kənˈviːniənt]', 'B1', 'ADJECTIVE'),
    ('Creative', 'Креативный;Творческий', '[kri(ː)ˈeɪtɪv]', 'B1', 'ADJECTIVE'),
    ('Naughty', 'Озорной;Шаловливый', '[ˈnɔːti]', 'B1', 'ADJECTIVE'),
    ('Stationary', 'Стационарный', '[ˈsteɪʃnəri]', 'B1', 'ADJECTIVE'),
    ('Valuable', 'Ценный', '[ˈvæljʊəbl]', 'B1', 'ADJECTIVE'),
    ('Significant', 'Значительный;Существенный', '[sɪgˈnɪfɪkənt]', 'B1', 'ADJECTIVE'),
    ('Foremost', 'Передовой;Основной;Главный', '[ˈfɔːməʊst]', 'B1', 'ADJECTIVE'),
    ('Recent', 'Недавний', '[ˈriːsnt]', 'B1', 'ADJECTIVE'),
    ('Updated', 'Обновленный', '[ʌpˈdeɪtɪd]', 'B1', 'ADJECTIVE'),
    ('Operational', 'Оперативный;Рабочий;Действующий', '[ˌɒpəˈreɪʃənl]', 'B1', 'ADJECTIVE'),
    ('Intuitive', 'Интуитивно понятный;Интуитивный', '[ɪnˈtju(ː)ɪtɪv]', 'B1', 'ADJECTIVE'),
    ('Essential', 'Существенный;Важный', '[ɪˈsɛnʃəl]', 'B1', 'ADJECTIVE'),
    ('Numerous', 'Многочисленный', '[ˈnjuːmərəs]', 'B1', 'ADJECTIVE'),
    ('Compliant', 'Соответствующий', '[kəmˈplaɪənt]', 'B1', 'ADJECTIVE'),
    ('Straightforward', 'Прямой;Прямолинейный', '[streɪtˈfɔːwəd]', 'B1', 'ADJECTIVE'),
    ('Understandable', 'Понятный;Доступный', '[ʌndəˈstændəbl]', 'B1', 'ADJECTIVE'),
    ('Uncompromising', 'Беспрекословный', '[ʌnˈkɒmprəmaɪzɪŋ]', 'B1', 'ADJECTIVE'),
    ('Distinguished', 'Выдающийся;Уважаемый;Отличительный', '[dɪsˈtɪŋgwɪʃt]', 'B1', 'ADJECTIVE'),
    ('Separate', 'Отдельный', '[ˈsɛprɪt]', 'B1', 'ADJECTIVE'),
    ('Outstanding', 'Незаурядный', '[aʊtˈstændɪŋ]', 'B1', 'ADJECTIVE'),
    ('Principal', 'Принципиальный;Главный', '[ˈprɪnsəpəl]', 'B1', 'ADJECTIVE'),
    ('Leading', 'Ведущий;Лидирующий', '[ˈliːdɪŋ]', 'B1', 'ADJECTIVE'),
    ('Cognitive', 'Когнитивный;Познавательный', '[ˈkɒgnɪtɪv]', 'B1', 'ADJECTIVE'),
    ('Cutting-edge', 'Современный;Новейший', '[kʌtɪŋ-ɛʤ]', 'B1', 'ADJECTIVE'),
    ('Precise', 'Точный;Четкий', '[prɪˈsaɪs]', 'B1', 'ADJECTIVE'),
    ('Unmatched', 'Неповторимый;Непревзойденный', '[ʌnˈmæʧt]', 'B1', 'ADJECTIVE'),
    ('Reasonable', 'Разумный;Целесообразный', '[ˈriːznəbl]', 'B1', 'ADJECTIVE'),
    ('Fundamental', 'Основополагающий', '[ˌfʌndəˈmɛntl]', 'B1', 'ADJECTIVE'),
    ('Brilliant', 'Блестящий;Гениальный', '[ˈbrɪljənt]', 'B1', 'ADJECTIVE'),
    ('Inflexible', 'Несгибаемый;Непогрешимый', '[ɪnˈflɛksəbl]', 'B1', 'ADJECTIVE'),
    ('Crucial', 'Решающий;Критический;Важный', '[ˈkruːʃəl]', 'B1', 'ADJECTIVE'),
    ('Contemporary', 'Современный;Актуальный', '[kənˈtɛmpərəri]', 'B1', 'ADJECTIVE'),
    ('Duplicated', 'Дублированный', '[ˈdjuːplɪkeɪtɪd]', 'B1', 'ADJECTIVE'),
    ('Tedious', 'Утомительный;Кропотливый;Надоедливый', '[ˈtiːdiəs]', 'B1', 'ADJECTIVE'),
    ('Multiple', 'Множественный;Многочисленный', '[ˈmʌltɪpl]', 'B1', 'ADJECTIVE'),
    ('Individual', 'Личный;Индивидуальный', '[ˌɪndɪˈvɪdjʊəl]', 'B1', 'ADJECTIVE'),
    ('Fitting', 'Подходящий', '[ˈfɪtɪŋ]', 'B1', 'ADJECTIVE'),
    ('Monotonous', 'Монотонный;Однообразный', '[məˈnɒtnəs]', 'B1', 'ADJECTIVE'),
    ('Ruthless', 'Бесчеловечный', '[ˈruːθlɪs]', 'B1', 'ADJECTIVE'),
    ('Multi-channel', 'Многоканальный', '[ˈmʌltɪ-ˈʧænl]', 'B1', 'ADJECTIVE'),
    ('Astonishing', 'Удивительный;Изумительный', '[əsˈtɒnɪʃɪŋ]', 'B1', 'ADJECTIVE'),
    ('Ambitious', 'Амбициозный;Честолюбивый', '[æmˈbɪʃəs]', 'B1', 'ADJECTIVE'),
    ('Captivating', 'Захватывающий;Завораживающий', '[ˈkæptɪveɪtɪŋ]', 'B1', 'ADJECTIVE'),
    ('Profound', 'Глубокомысленный', '[prəˈfaʊnd]', 'B1', 'ADJECTIVE'),
    ('Qualified', 'Квалифицированный', '[ˈkwɒlɪfaɪd]', 'B1', 'ADJECTIVE'),
    ('Remarkable', 'Замечательный;Примечательный;Выдающийся', '[rɪˈmɑːkəbl]', 'B1', 'ADJECTIVE'),
    ('Additional', 'Дополнительный', '[əˈdɪʃənl]', 'B1', 'ADJECTIVE'),
    ('Burning', 'Горящий;Жгучий', '[ˈbɜːnɪŋ]', 'B1', 'ADJECTIVE'),
    ('Unassuming', 'Непритязательный', '[ˌʌnəˈsjuːmɪŋ]', 'B1', 'ADJECTIVE'),
    ('Meaningful', 'Значимый;Осмысленный', '[ˈmiːnɪŋfʊl]', 'B1', 'ADJECTIVE'),
    ('Private', 'Личный;Частный', '[ˈpraɪvɪt]', 'B1', 'ADJECTIVE'),
    ('Careful', 'Бережный;Осторожный', '[ˈkeəfʊl]', 'B1', 'ADJECTIVE'),
    ('Obscure', 'Наблюдательный;Непонятный', '[əbˈskjʊə]', 'B1', 'ADJECTIVE'),
    ('Accomplished', 'Состоятельный;Успешный;Достигнутый', '[əˈkɒmplɪʃt]', 'B1', 'ADJECTIVE'),
    ('Ridiculous', 'Нелепый;Смешной', '[rɪˈdɪkjʊləs]', 'B1', 'ADJECTIVE'),
    ('Contemptuous', 'Презрительный', '[kənˈtɛmptjʊəs]', 'B1', 'ADJECTIVE'),
    ('Fashionable', 'Модный', '[ˈfæʃnəbl]', 'B1', 'ADJECTIVE');

-- Adverb наречие
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
    ('Invariably', 'Неизменно', '[ɪnˈveərɪəbli]', 'B1', 'ADVERB'),
    ('Intermittently', 'Иногда', '[ɪntə(ː)ˈmɪtəntli]', 'B1', 'ADVERB'),
    ('Infrequently', 'Редко', '[ɪntə(ː)ˈmɪtəntli]', 'B1', 'ADVERB'),
    ('Predominantly', 'Постоянно', '[prɪˈdɒmɪnəntli]', 'B1', 'ADVERB'),
    ('Elsewhere', 'Где-нибудь', '[ˈɛlsˈweə]', 'B1', 'ADVERB'),
    ('Scarcely', 'Едва', '[ ˈskeəsli]', 'B1', 'ADVERB'),
    ('Otherwise', 'Иначе', '[ˈʌðəwaɪz]', 'B1', 'ADVERB'),
    ('Quickly', 'Быстро', '[ˈkwɪkli]', 'B1', 'ADVERB'),
    ('Quietly', 'Спокойно;Тихо', '[ˈkwaɪətli]', 'B1', 'ADVERB'),
    ('Moreover', 'Более того', '[mɔːˈrəʊvə]', 'B1', 'ADVERB'),
    ('Nevertheless', 'Тем не менее', '[ˌnɛvəðəˈlɛs]', 'B1', 'ADVERB'),
    ('Somewhat', 'До некоторой степени', '[ˈsʌmwɒt]', 'B1', 'ADVERB'),
    ('Cheerfully', 'Весело', '[ˈʧɪəfʊli]', 'B1', 'ADVERB'),
    ('Clumsily', 'Неуклюже', '[klʌmzɪli]', 'B1', 'ADVERB'),
    ('In vain', 'Напрасно', '[ɪn veɪn]', 'B1', 'ADVERB'),
    ('At once', 'Немедленно', '[æt wʌns]', 'B1', 'ADVERB'),
    ('Casually', 'Случайно', '[ˈkæʒjʊəli]', 'B1', 'ADVERB'),
    ('Since that', 'С тех пор', '[sɪns ðæt]', 'B1', 'ADVERB'),
    ('By all means', 'Во что бы то ни стало', '[baɪ ɔːl miːnz]', 'B1', 'ADVERB'),
    ('Readily', 'Охотно', '[ˈrɛdɪli]', 'B1', 'ADVERB'),
    ('Outside', 'Снаружи', '[ˌaʊtˈsaɪd]', 'B1', 'ADVERB'),
    ('Besides', 'Кроме того', '[bɪˈsaɪdz]', 'B1', 'ADVERB'),
    ('Once', 'Однажды', '[wʌns]', 'B1', 'ADVERB'),
    ('However', 'Однако;Как бы ни', '[haʊˈɛvə]', 'B1', 'ADVERB'),
    ('Yet', 'Еще;До сих пор', '[jɛt]', 'B1', 'ADVERB'),
    ('Foolishly', 'Глупо;По глупости', '[ˈfuːlɪʃli]', 'B1', 'ADVERB'),
    ('Clearly', 'Очевидно', '[ˈklɪəli]', 'B1', 'ADVERB'),
    ('Actually', 'В общем;Вообще-то', '[ˈækʧʊəli]', 'B1', 'ADVERB'),
    ('Completely', 'Совершенно;Абсолютно', '[kəmˈpliːtli]', 'B1', 'ADVERB'),
    ('Extremely', 'Безумно', '[ɪksˈtriːmli]', 'B1', 'ADVERB'),
    ('Nearby', 'Рядом;Неподалеку', '[ˈnɪəbaɪ]', 'B1', 'ADVERB'),
    ('Unmistakable', 'Безошибочно', '[ʌnmɪsˈteɪkəbl]', 'B1', 'ADVERB'),
    ('Accurately', 'Точно', '[ˈækjʊrɪtli]', 'B1', 'ADVERB'),
    ('Definitely', 'Абсолютно', '[ˈdɛfɪnɪtli]', 'B1', 'ADVERB'),
    ('Relentlessly', 'Безостановочно', '[rɪˈlɛntlɪsli]', 'B1', 'ADVERB'),
    ('Incredibly', 'Невероятно;Очень;Неимоверно', '[ɪnˈkrɛdəbli]', 'B1', 'ADVERB'),
    ('Decidedly', 'Решительно', '[dɪˈsaɪdɪdli]', 'B1', 'ADVERB'),
    ('Firmly', 'Уверенно', '[ˈfɜːmli]', 'B1', 'ADVERB'),
    ('Carelessly', 'Беспечно', '[ˈkeəlɪsli]', 'B1', 'ADVERB'),
    ('Nevertheless', 'Тем не менее', '[nɛvəðəˈlɛs]', 'B1', 'ADVERB');
    