-- Глаголы VERB
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES ('To be', 'Быть', '[tə biː]', 'A1', 'VERB'),
('To do', 'Делать', '[du]', 'A1', 'VERB'),
('To feel', 'Чувствовать', '[fiːl]', 'A1', 'VERB'),
('To see', 'Видеть', '[siː]', 'A1', 'VERB'),
('To hear', 'Слышать', '[hɪər]', 'A1', 'VERB'),
('To run', 'Бежать', '[rʌn]', 'A1', 'VERB'),
('To get', 'Получать', '[ɡet]', 'A1', 'VERB'),
('To make', 'Сделать', '[meɪk]', 'A1', 'VERB'),
('To cook', 'Готовить', '[kʊk]', 'A1', 'VERB'),
('To sing', 'Петь', '[sɪŋ]', 'A1', 'VERB'),
('To speak', 'Разговаривать', '[spiːk]', 'A1', 'VERB'),
('To say', 'Говорить', '[seɪ]', 'A1', 'VERB'),
('To tell', 'Рассказывать', '[tel]', 'A1', 'VERB'),
('To take', 'Брать', '[teɪk]', 'A1', 'VERB'),
('To sit', 'Садиться', '[sɪt]', 'A1', 'VERB'),
('To stand', 'Стоять', '[stænd]', 'A1', 'VERB'),
('To laugh', 'Смеяться', '[lɑːf]', 'A1', 'VERB'),
('To smile', 'Улыбаться', '[smaɪl]', 'A1', 'VERB'),
('To open', 'Открывать', '[ˈəʊpən]', 'A1', 'VERB'),
('To close', 'Закрывать', '[kləʊz]', 'A1', 'VERB'),
('To love', 'Любить', '[lʌv]', 'A1', 'VERB'),
('To like', 'Нравиться', '[laɪk]', 'A1', 'VERB'),
('To give', 'Давать', '[ɡɪv]', 'A1', 'VERB'),
('To bring', 'Приносить', '[brɪŋ]', 'A1', 'VERB'),
('To breath', 'Дышать', '[breθ]', 'A1', 'VERB'),
('To buy', 'Покупать', '[baɪ]', 'A1', 'VERB'),
('To sell', 'Продавать', '[sel]', 'A1', 'VERB'),
('To forget', 'Забывать', '[fəˈɡet]', 'A1', 'VERB'),
('To believe', 'Верить', '[bɪˈliːv]', 'A1', 'VERB'),
('To have', 'Иметь', '[həv]', 'A1', 'VERB'),
('To go', 'Идти', '[ɡəʊ]', 'A1', 'VERB'),
('To know', 'Знать', '[nəʊ]', 'A1', 'VERB'),
('To think', 'Думать', '[θɪŋk]', 'A1', 'VERB'),
('To come', 'Приходить', '[kʌm]', 'A1', 'VERB'),
('To want', 'Хотеть', '[wɒnt]', 'A1', 'VERB'),
('To use', 'Использовать', '[juːz]', 'A1', 'VERB'),
('To find', 'Находить', '[faɪnd]', 'A1', 'VERB'),
('To work', 'Работать', '[wɜːk]', 'A1', 'VERB'),
('To eat', 'Есть', '[iːt]', 'A1', 'VERB'),
('To drink', 'Пить', '[drɪŋk]', 'A1', 'VERB'),
('To write', 'Писать', '[raɪt]', 'A1', 'VERB'),
('To read', 'Читать', '[riːd]', 'A1', 'VERB'),
('To call', 'Звонить', '[kɔːl]', 'A1', 'VERB'),
('To try', 'Пытаться', '[traɪ]', 'A1', 'VERB'),
('To need', 'Нуждаться', '[niːd]', 'A1', 'VERB'),
('To become', 'Становиться', '[bɪˈkʌm]', 'A1', 'VERB'),
('To put', 'Класть', '[pʊt]', 'A1', 'VERB'),
('To leave', 'Оставлять', '[liːv]', 'A1', 'VERB'),
('To pay', 'Платить', '[peɪ]', 'A1', 'VERB'),
('To play', 'Играть', '[pleɪ]', 'A1', 'VERB'),
('To pray', 'Молиться', '[preɪ]', 'A1', 'VERB'),
('To stay', 'Оставаться', '[steɪ]', 'A1', 'VERB'),
('To mean', 'Означать', '[miːn]', 'A1', 'VERB'),
('To keep', 'Держать;Хранить', '[kiːp]', 'A1', 'VERB'),
('To let', 'Оставлять', '[let]', 'A1', 'VERB'),
('To begin', 'Начинать', '[bɪˈɡɪn]', 'A1', 'VERB'),
('To start', 'Стартовать', '[stɑːt]', 'A1', 'VERB'),
('To finish', 'Заканчивать', '[ˈfɪnɪʃ]', 'A1', 'VERB'),
('To help', 'Помогать', '[help]', 'A1', 'VERB'),
('To show', 'Показывать', '[ʃəʊ]', 'A1', 'VERB'),
('To cry', 'Плакать', '[kraɪ]', 'A1', 'VERB'),
('To move', 'Двигаться', '[muːv]', 'A1', 'VERB'),
('To jump', 'Прыгать', '[dʒʌmp]', 'A1', 'VERB'),
('To live', 'Жить', '[lɪv]', 'A1', 'VERB'),
('To die', 'Умирать', '[daɪ]', 'A1', 'VERB'),
('To happen', 'Случаться', '[ˈhæpən]', 'A1', 'VERB'),
('To lose', 'Проигрывать', '[luːz]', 'A1', 'VERB'),
('To hate', 'Ненавидеть', '[heɪt]', 'A1', 'VERB'),
('To include', 'Включать в себя', '[ɪnˈkluːd]', 'A1', 'VERB'),
('To turn on', 'Включать', '[tɜːn ɒn]', 'A1', 'VERB'),
('To turn off', 'Выключать', '[tɜːn ɒf]', 'A1', 'VERB'),
('To continue', 'Продолжать', '[kənˈtɪnjuː]', 'A1', 'VERB'),
('To change', 'Менять', '[tʃeɪndʒ]', 'A1', 'VERB'),
('To wash', 'Мыть', '[wɒʃ]', 'A1', 'VERB'),
('To clean', 'Убирать;Очищать', '[kliːn]', 'A1', 'VERB'),
('To lead', 'Вести', '[liːd]', 'A1', 'VERB'),
('To understand', 'Понимать', '[ˌʌndəˈstænd]', 'A1', 'VERB'),
('To watch', 'Смотреть', '[wɒtʃ]', 'A1', 'VERB'),
('To discover', 'Исследовать', '[dɪˈskʌvə(r)]', 'A1', 'VERB'),
('To imagine', 'Представлять', '[ɪˈmædʒɪn]', 'A1', 'VERB'),
('To introduce', 'Представить', '[ˌɪntrəˈdjuːs]', 'A1', 'VERB'),
('To follow', 'Следовать', '[ˈfɒləʊ]', 'A1', 'VERB'),
('To create', 'Создавать', '[kriˈeɪt]', 'A1', 'VERB'),
('To grow', 'Расти', '[ɡrəʊ]', 'A1', 'VERB'),
('To spend', 'Тратить', '[spend]', 'A1', 'VERB'),
('To win', 'Выигрывать', '[wɪn]', 'A1', 'VERB'),
('To offer', 'Предлагать', '[ˈɒfə(r)]', 'A1', 'VERB'),
('To learn', 'Изучать', '[lɜːn]', 'A1', 'VERB'),
('To appear', 'Появляться', '[əˈpɪə(r)]', 'A1', 'VERB'),
('To disappear', 'Исчезать', '[ˌdɪsəˈpɪə(r)]', 'A1', 'VERB'),
('To build', 'Строить', '[bɪld]', 'A1', 'VERB'),
('To break', 'Ломать', '[breɪk]', 'A1', 'VERB'),
('To send', 'Посылать', '[send]', 'A1', 'VERB'),
('To fall', 'Падать', '[fɔːl]', 'A1', 'VERB'),
('To cut', 'Резать', '[kʌt]', 'A1', 'VERB'),
('To achieve', 'Достигать', '[əˈtʃiːv]', 'A1', 'VERB'),
('To communicate', 'Общаться', '[kəˈmjuːnɪkeɪt]', 'A1', 'VERB'),
('To kill', 'Убивать', '[kɪl]', 'A1', 'VERB'),
('To pass', 'Проходить', '[pɑːs]', 'A1', 'VERB'),
('To fly', 'Летать', '[flaɪ]', 'A1', 'VERB'),
('To swim', 'Плавать', '[swɪm]', 'A1', 'VERB'),
('To decide', 'Решать', '[dɪˈsaɪd]', 'A1', 'VERB'),
('To return', 'Возвращаться', '[rɪˈtɜːn]', 'A1', 'VERB'),
('To hope', 'Надеяться', '[həʊp]', 'A1', 'VERB'),
('To explain', 'Объяснять', '[ɪkˈspleɪn]', 'A1', 'VERB'),
('To propose', 'Предлагать', '[prəˈpəʊz]', 'A1', 'VERB'),
('To develop', 'Развивать', '[dɪˈveləp]', 'A1', 'VERB'),
('To support', 'Поддерживать', '[səˈpɔːt]', 'A1', 'VERB'),
('To dance', 'Танцевать', '[dɑːns]', 'A1', 'VERB'),
('To draw', 'Рисовать', '[drɔː]', 'A1', 'VERB'),
('To book', 'Бронировать', '[bʊk]', 'A1', 'VERB'),
('To be afraid', 'Бояться', '[bi əˈfreɪd]', 'A1', 'VERB'),
('To agree', 'Соглашаться', '[əˈɡriː]', 'A1', 'VERB'),
('To check up', 'Проверять', '[tʃek ʌp]', 'A1', 'VERB'),
('To delete', 'Удалять', '[dɪˈliːt]', 'A1', 'VERB'),
('To choose', 'Выбирать', '[tʃuːz]', 'A1', 'VERB'),
('To catch', 'Ловить', '[kætʃ]', 'A1', 'VERB'),
('To ask', 'Спрашивать', '[ɑːsk]', 'A1', 'VERB'),
('To answer', 'Отвечать', '[ˈɑːnsə(r)]', 'A1', 'VERB'),
('To hesitate', 'Сомневаться', '[ˈhezɪteɪt]', 'A1', 'VERB');

-- существительные NOUN
-- 
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES ('Air', 'Воздух', '[ən eə(r)]', 'A1', 'NOUN'),
    ('Wind', 'Ветер', '[wɪnd]', 'A1', 'NOUN'),
    ('Water', 'Вода', '[ˈwɔːtə(r)]', 'A1', 'NOUN'),
    ('West', 'Запад', '[west]', 'A1', 'NOUN'),
    ('East', 'Восток', '[iːst]', 'A1', 'NOUN'),
    ('North', 'Север', '[nɔːθ]', 'A1', 'NOUN'),
    ('South', 'Юг', '[saʊθ]', 'A1', 'NOUN'),
    ('Tree', 'Дерево', '[triː]', 'A1', 'NOUN'),
    ('Sea', 'Море', '[siː]', 'A1', 'NOUN'),
    ('Ocean', 'Океан', '[ˈəʊʃn]', 'A1', 'NOUN'),
    ('Rock', 'Скала', '[rɒk]', 'A1', 'NOUN'),
    ('Plant', 'Растение', '[plɑːnt]', 'A1', 'NOUN'),
    ('Flower', 'Цветок', '[ˈflaʊə(r)]', 'A1', 'NOUN'),
    ('Forest', 'Лес', '[ˈfɒrɪst]', 'A1', 'NOUN'),
    ('Person', 'Личность', '[ˈpɜːsn]', 'A1', 'NOUN'),
    ('Night', 'Ночь', '[naɪt]', 'A1', 'NOUN'),
    ('Morning', 'Утро', '[ˈmɔːnɪŋ]', 'A1', 'NOUN'),
    ('Day', 'День', '[deɪ]', 'A1', 'NOUN'),
    ('Evening', 'Вечер', '[ˈiːvnɪŋ]', 'A1', 'NOUN'),
    ('Life', 'Жизнь', '[laɪf]', 'A1', 'NOUN'),
    ('Mountain', 'Гора', '[ˈmaʊntən]', 'A1', 'NOUN'),
    ('Land', 'Земля', '[lænd]', 'A1', 'NOUN'),
    ('House', 'Дом', '[haʊs]', 'A1', 'NOUN'),
    ('Fire', 'Огонь', '[ˈfaɪə(r)]', 'A1', 'NOUN'),
    ('Country', 'Страна', '[ˈkʌntri]', 'A1', 'NOUN'),
    ('Animal', 'Животное', '[ˈænɪml]', 'A1', 'NOUN'),
    ('Bird', 'Птица', '[bɜːd]', 'A1', 'NOUN'),
    ('Fish', 'Рыба', '[fɪʃ]', 'A1', 'NOUN'),
    ('Insect', 'Насекомое', '[ˈɪnsekt]', 'A1', 'NOUN'),
    ('City', 'Город', '[ˈsɪti]', 'A1', 'NOUN'),
    ('World', 'Мир', '[wɜːld]', 'A1', 'NOUN'),
    ('Boy', 'Мальчик', '[bɔɪ]', 'A1', 'NOUN'),
    ('Girl', 'Девочка', '[ɡɜːl]', 'A1', 'NOUN'),
    ('Mother', 'Мама', '[ˈmʌðə(r)]', 'A1', 'NOUN'),
    ('Father', 'Отец', '[ˈfɑːðə(r)]', 'A1', 'NOUN'),
    ('Son', 'Сын', '[sʌn]', 'A1', 'NOUN'),
    ('Daughter', 'Дочь', '[ˈdɔːtə(r)]', 'A1', 'NOUN'),
    ('Baby', 'Малыш', '[ˈbeɪbi]', 'A1', 'NOUN'),
    ('Family', 'Семья', '[ˈfæməli]', 'A1', 'NOUN'),
    ('Grand mother', 'Бабушка', '[ɡrænd ˈməT͟Hər]', 'A1', 'NOUN'),
    ('Grand father', 'Дедушка', '[ɡrænd ˈfɑːðə(r)]', 'A1', 'NOUN'),
    ('Children', 'Дети', '[ˈtʃɪl.drən]', 'A1', 'NOUN'),
    ('Home', 'Дом', '[həʊm]', 'A1', 'NOUN'),
    ('Love', 'Любовь', '[lʌv]', 'A1', 'NOUN'),
    ('Apartment', 'Квартира', '[əˈpɑːtmənt]', 'A1', 'NOUN'),
    ('Joy', 'Радость', '[dʒɔɪ]', 'A1', 'NOUN'),
    ('Nephew', 'Племянник', '[ˈnefjuː]', 'A1', 'NOUN'),
    ('Aunt', 'Тетя', '[ɑːnt]', 'A1', 'NOUN'),
    ('Uncle', 'Дядя', '[ˈʌŋkl]', 'A1', 'NOUN'),
    ('Cousin', 'Двоюродная сестра;Двоюродный брат', '[ˈkʌzn]', 'A1', 'NOUN'),
    ('Man', 'Мужчина', '[mæn]', 'A1', 'NOUN'),
    ('Woman', 'Женщина', '[ˈwʊmən]', 'A1', 'NOUN'),
    ('Child', 'Ребенок', '[tʃaɪld]', 'A1', 'NOUN'),
    ('Sister', 'Сестра', '[ˈsɪstə(r)]', 'A1', 'NOUN'),
    ('Brother', 'Брат', '[ˈbrʌðə(r)]', 'A1', 'NOUN'),
    ('Relatives', 'Родственники', '[ˈrel.ə.tɪv]', 'A1', 'NOUN'),
    ('Friend', 'Друг', '[frend]', 'A1', 'NOUN'),
    ('Wife', 'Жена', '[waɪf]', 'A1', 'NOUN'),
    ('Husband', 'Муж', '[ˈhʌzbənd]', 'A1', 'NOUN'),
    ('Address', 'Адрес', '[əˈdres]', 'A1', 'NOUN'),
    ('Happiness', 'Счастье', '[ˈhæp.i.nəs]', 'A1', 'NOUN'),
    ('People', 'Люди', '[ˈpiːpl]', 'A1', 'NOUN'),
    ('Phone', 'Телефон', '[fəʊn]', 'A1', 'NOUN'),
    ('Question', 'Вопрос', '[ˈkwestʃən]', 'A1', 'NOUN'),
    ('Place', 'Место', '[pleɪs]', 'A1', 'NOUN'),
    ('Market', 'Рынок', '[ˈmɑːkɪt]', 'A1', 'NOUN'),
    ('Order', 'Заказ', '[ˈɔːdə(r)]', 'A1', 'NOUN'),
    ('Food', 'Еда', '[fuːd]', 'A1', 'NOUN'),
    ('Work', 'Работа', '[wɜːk]', 'A1', 'NOUN'),
    ('Communication', 'Общение', '[kəˌmjuːnɪˈkeɪʃn]', 'A1', 'NOUN'),
    ('Story', 'История', '[ˈstɔːri]', 'A1', 'NOUN'),
    ('Relax', 'Отдых', '[rɪˈlæks]', 'A1', 'NOUN'),
    ('Time', 'Время', '[taɪm]', 'A1', 'NOUN'),
    ('Word', 'Слово', '[wɜːd]', 'A1', 'NOUN'),
    ('Dialogue', 'Диалог', '[ˈdaɪ.ə.lɒɡ]', 'A1', 'NOUN'),
    ('Meeting', 'Встреча', '[ˈmiːtɪŋ]', 'A1', 'NOUN'),
    ('Week', 'Неделя', '[wiːk]', 'A1', 'NOUN'),
    ('Distance', 'Дистанция', '[ˈdɪstəns]', 'A1', 'NOUN'),
    ('Club', 'Клуб', '[klʌb]', 'A1', 'NOUN'),
    ('Theatre', 'Театр', '[ˈθɪətə(r)]', 'A1', 'NOUN'),
    ('Cinema', 'Кинотеатр', '[ˈsɪnəmə]', 'A1', 'NOUN'),
    ('Coffee shop', 'Кофейня', '[ˈkɒfi ʃɒp]', 'A1', 'NOUN'),
    ('Friendship', 'Дружба', '[ˈfrendʃɪp]', 'A1', 'NOUN'),
    ('Behavior', 'Поведение', '[bɪˈheɪ.vjər]', 'A1', 'NOUN'),
    ('Attitude', 'Отношение', '[ˈætɪtjuːd]', 'A1', 'NOUN'),
    ('Student', 'Студент', '[ˈstjuːdnt]', 'A1', 'NOUN'),
    ('University', 'Университет', '[ˌjuːnɪˈvɜːsəti]', 'A1', 'NOUN'),
    ('Union', 'Объединение', '[ˈjuːniən]', 'A1', 'NOUN'),
    ('Party', 'Вечеринка', '[ˈpɑːti]', 'A1', 'NOUN'),
    ('Date', 'Свидание', '[deɪt]', 'A1', 'NOUN'),
    ('Sweetheart', 'Партнер;Возлюбленный', '[ˈswiːt.hɑːt]', 'A1', 'NOUN'),
    ('Leisure time', 'Досуг', '[ˈleʒ.ər taɪm]', 'A1', 'NOUN'),
    ('Road', 'Дорога', '[rəʊd]', 'A1', 'NOUN'),
    ('Ticket', 'Билет', '[ˈtɪkɪt]', 'A1', 'NOUN'),
    ('Map', 'Карта', '[mæp]', 'A1', 'NOUN'),
    ('Motel', 'Мотель', '[məʊˈtel]', 'A1', 'NOUN'),
    ('Highway', 'Шоссе', '[ˈhaɪweɪ]', 'A1', 'NOUN'),
    ('Reception', 'Регистратура;Ресепшн', '[rɪˈsepʃn]', 'A1', 'NOUN'),
    ('Wallet', 'Бумажник', '[ˈwɒlɪt]', 'A1', 'NOUN'),
    ('Bank', 'Банк', '[bæŋk]', 'A1', 'NOUN'),
    ('Subway', 'Метро', '[ˈsʌb.weɪ]', 'A1', 'NOUN'),
    ('Cab', 'Такси', '[kæb]', 'A1', 'NOUN'),
    ('Parking', 'Парковка', '[ˈpɑː.kɪŋ]', 'A1', 'NOUN'),
    ('Food order', 'Заказ еды', '[fuːd ˈɔːdə(r)]', 'A1', 'NOUN'),
    ('Cash', 'Наличные', '[kæʃ]', 'A1', 'NOUN'),
    ('Passport', 'Паспорт', '[ˈpɑːspɔːt]', 'A1', 'NOUN'),
    ('Permission', 'Разрешение', '[pəˈmɪʃn]', 'A1', 'NOUN'),
    ('Lawyer', 'Адвокат', '[ˈlɔːjə(r)]', 'A1', 'NOUN'),
    ('Problem', 'Проблема', '[ˈprɒbləm]', 'A1', 'NOUN'),
    ('Waiting room', 'Зал ожидания', '[weɪtin: ruːm]', 'A1', 'NOUN'),
    ('Transfer', 'Пересадка', '[trænsˈfɜː(r)]', 'A1', 'NOUN'),
    ('Bag', 'Сумка', '[bæɡ]', 'A1', 'NOUN'),
    ('Suitcase', 'Чемодан', '[ˈsuːtkeɪs]', 'A1', 'NOUN'),
    ('Property', 'Имущество', '[ˈprɒpəti]', 'A1', 'NOUN'),
    ('Law', 'Право;Закон', '[lɔː]', 'A1', 'NOUN'),
    ('Police station', 'Полицейский участок', '[pəˈliːs ˈsteɪʃn]', 'A1', 'NOUN'),
    ('Price', 'Стоимость;Цена', '[praɪs]', 'A1', 'NOUN'),
    ('Price list', 'Ценник', '[praɪs lɪst]', 'A1', 'NOUN'),
    ('Courier', 'Курьер', '[ˈkʊr.i.ər]', 'A1', 'NOUN'),
    ('Delivery', 'Доставка', '[dɪˈlɪvəri]', 'A1', 'NOUN'),
    ('Location', 'Местоположение', '[ləʊˈkeɪʃn]', 'A1', 'NOUN'),
    ('Route', 'Маршрут', '[ruːt]', 'A1', 'NOUN'),
    ('Agreement', 'Договор', '[əˈɡriːmənt]', 'A1', 'NOUN'),
    ('Hospital', 'Больница', '[ˈhɒspɪtl]', 'A1', 'NOUN'),
    ('Ambulance', 'Скорая помощь', '[ˈæmbjələns]', 'A1', 'NOUN');

-- adjectives прилагательный


INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES
('Afraid', 'Напуганный', '[əˈfreɪd]', 'A1', 'ADJECTIVE'),
( 'Angry', 'Сердитый', '[əˈfreɪd]', 'A1', 'ADJECTIVE' ),
( 'Asleep', 'Спящий', '[əˈsliːp]', 'A1', 'ADJECTIVE' ),
( 'Attentive', 'Внимательный', '[əˈten.tɪv]', 'A1', 'ADJECTIVE' ),
( 'Available', 'Доступный', '[əˈveɪləbl]', 'A1', 'ADJECTIVE' ),
( 'Basic', 'Базовый', '[ˈbeɪsɪk]', 'A1', 'ADJECTIVE' ),
( 'Beautiful', 'Красивый', '[ˈbjuːtɪfl]', 'A1', 'ADJECTIVE' ),
( 'Big', 'Большой', '[bɪɡ]', 'A1', 'ADJECTIVE' ),
( 'Brave', 'Смелый', '[breɪv]', 'A1', 'ADJECTIVE' ),
( 'Busy', 'Занятой', '[ˈbɪzi]', 'A1', 'ADJECTIVE' ),
( 'Calm', 'Спокойный', '[kɑːm]', 'A1', 'ADJECTIVE' ),
( 'Careful', 'Внимательный;Заботоливый', '[ˈkeəfl]', 'A1', 'ADJECTIVE' ),
( 'Cheap', 'Дешевый', '[tʃiːp]', 'A1', 'ADJECTIVE' ),
( 'Clean', 'Чистый', '[kliːn]', 'A1', 'ADJECTIVE' ),
( 'Clever', 'Умный', '[ˈklevə(r)]', 'A1', 'ADJECTIVE' ),
( 'Cold', 'Холодный', '[kəʊld]', 'A1', 'ADJECTIVE' ),
( 'Comfortable', 'Комфортный', '[ˈkʌmftəbl]', 'A1', 'ADJECTIVE' ),
( 'Confident', 'Уверенный', '[ˈkɒnfɪdənt]', 'A1', 'ADJECTIVE' ),
( 'Constant', 'Постоянный', '[ˈkɒnstənt]', 'A1', 'ADJECTIVE' ),
( 'Curious', 'Любопытный', '[ˈkjʊəriəs]', 'A1', 'ADJECTIVE' ),
( 'Dangerous', 'Опасный', '[ˈdeɪndʒərəs]', 'A1', 'ADJECTIVE' ),
( 'Dark', 'Темный', '[dɑːk]', 'A1', 'ADJECTIVE' ),
( 'Deep', 'Глубокий', '[diːp]', 'A1', 'ADJECTIVE' ),
( 'Different', 'Разный', '[ˈdɪfrənt]', 'A1', 'ADJECTIVE' ),
( 'Difficult', 'Трудный', '[ˈdɪfɪkəlt]', 'A1', 'ADJECTIVE' ),
( 'Dirty', 'Грязный', '[ˈdɜːti]', 'A1', 'ADJECTIVE' ),
( 'Easy', 'Легкий', '[ˈiːzi]', 'A1', 'ADJECTIVE' ),
( 'Every', 'Каждый', '[ˈevri]', 'A1', 'ADJECTIVE' ),
( 'Expensive', 'Дорогой', '[ɪkˈspensɪv]', 'A1', 'ADJECTIVE' ),
( 'Exact', 'Точный', '[ɪɡˈzækt]', 'A1', 'ADJECTIVE' ),
( 'Fast', 'Быстрый', '[fɑːst]', 'A1', 'ADJECTIVE' ),
( 'Fair', 'Честный;Светлый', '[feə(r)]', 'A1', 'ADJECTIVE' ),
( 'Fine', 'Замечательный', '[faɪn]', 'A1', 'ADJECTIVE' ),
( 'Foreign', 'Иностранный', '[ˈfɒrən]', 'A1', 'ADJECTIVE' ),
( 'Free', 'Свободный', '[friː]', 'A1', 'ADJECTIVE' ),
( 'Fresh', 'Свежий', '[freʃ]', 'A1', 'ADJECTIVE' ),
( 'Full', 'Полный', '[fʊl]', 'A1', 'ADJECTIVE' ),
( 'Funny', 'Забавный', '[ˈfʌni]', 'A1', 'ADJECTIVE' ),
( 'Guilty', 'Виновный', '[ˈɡɪlti]', 'A1', 'ADJECTIVE' ),
( 'Healthy', 'Здоровый', '[ˈhelθi]', 'A1', 'ADJECTIVE' ),
( 'Hard', 'Тяжелый', '[hɑːd]', 'A1', 'ADJECTIVE' ),
( 'Helpful', 'Полезный', '[ˈhelpfl]', 'A1', 'ADJECTIVE' ),
( 'Honest', 'Честный', '[ˈɒnɪst]', 'A1', 'ADJECTIVE' ),
( 'Hot', 'Горячий', '[hɒt]', 'A1', 'ADJECTIVE' ),
( 'Hungry', 'Голодный', '[ˈhʌŋɡri]', 'A1', 'ADJECTIVE' ),
( 'Important', 'Важный', '[ɪmˈpɔːtnt]', 'A1', 'ADJECTIVE' ),
( 'Illegal', 'Нелегальный;Незаконный', '[ɪˈliːɡl]', 'A1', 'ADJECTIVE' ),
( 'Impossible', 'Невозможный', '[ɪmˈpɒsəbl]', 'A1', 'ADJECTIVE' ),
( 'Independent', 'Независимый', '[ˌɪndɪˈpendənt]', 'A1', 'ADJECTIVE' ),
('Interesting', 'Интересный', '[ˈɪntrəstɪŋ]', 'A1', 'ADJECTIVE'),
('Kind', 'Добрый', '[kaɪnd]', 'A1', 'ADJECTIVE'),
('Legal', 'Законный', '[ˈliːɡl]', 'A1', 'ADJECTIVE'),
('Little', 'Маленький', '[ˈlɪtl]', 'A1', 'ADJECTIVE'),
('Lucky', 'Удачливый', '[ˈlʌki]', 'A1', 'ADJECTIVE'),
('Necessary', 'Необходимый', '[ˈnesəsəri]', 'A1', 'ADJECTIVE'),
('Normal', 'Нормальный', '[ˈnɔːml]', 'A1', 'ADJECTIVE'),
('Old', 'Старый', '[əʊld]', 'A1', 'ADJECTIVE'),
('Opposite', 'Противоположный', '[ˈɒpəzɪt]', 'A1', 'ADJECTIVE'),
('Perfect', 'Идеальный', '[pəˈfekt]', 'A1', 'ADJECTIVE'),
('Poor', 'Бедный', '[pɔː(r)]', 'A1', 'ADJECTIVE'),
('Powerful', 'Мощный', '[ˈpaʊəfl]', 'A1', 'ADJECTIVE'),
('Possible', 'Возможный', '[ˈpɒsəbl]', 'A1', 'ADJECTIVE'),
('Quiet', 'Тихий', '[ˈkwaɪət]', 'A1', 'ADJECTIVE'),
('Rare', 'Редкий', '[reə(r)]', 'A1', 'ADJECTIVE'),
('Recent', 'Недавний', '[ˈriːsnt]', 'A1', 'ADJECTIVE'),
('Relevant', 'Релевантный;Актуальный', '[ˈreləvənt]', 'A1', 'ADJECTIVE'),
('Remote', 'Удаленный', '[rɪˈməʊt]', 'A1', 'ADJECTIVE'),
('Safe', 'Безопасный', '[seɪf]', 'A1', 'ADJECTIVE'),
('Short', 'Короткий', '[ʃɔːt]', 'A1', 'ADJECTIVE'),
('Small', 'Маленький', '[smɔːl]', 'A1', 'ADJECTIVE'),
('Strange', 'Странный;Незнакомый;Чужой', '[streɪndʒ]', 'A1', 'ADJECTIVE'),
('Successful', 'Успешный', '[səkˈsesfl]', 'A1', 'ADJECTIVE'),
('Tasty', 'Вкусный;Приятный', '[ˈteɪ.sti]', 'A1', 'ADJECTIVE'),
('Terrible', 'Жуткий', '[ˈterəbl]', 'A1', 'ADJECTIVE'),
('Tired', 'Усталый', '[ˈtaɪəd]', 'A1', 'ADJECTIVE'),
('Warm', 'Теплый', '[wɔːm]', 'A1', 'ADJECTIVE'),
('Weak', 'Слабый', '[wiːk]', 'A1', 'ADJECTIVE'),
('Responsible', 'Ответственный;Надежный', '[rɪˈspɒnsəbl]', 'A1', 'ADJECTIVE'),
('Sad', 'Грустный', '[sæd]', 'A1', 'ADJECTIVE'),
('International', 'Международный', '[ˌɪntəˈnæʃnəl]', 'A1', 'ADJECTIVE');

-- наречия adverbs
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES 
('Together', 'Вместе', '[təˈɡeðə(r)]', 'A1', 'ADVERB'),
('According', 'В соответствии', '[əˈkɔːdɪŋ]', 'A1', 'ADVERB'), 
('Again', 'Снова', '[əˈɡen]', 'A1', 'ADVERB'), 
('Always', 'Всегда', '[ˈɔːlweɪz]', 'A1', 'ADVERB'), 
('Beautifully', 'Красиво', '[ˈbjuːtɪfli]', 'A1', 'ADVERB'), 
('Carefully', 'Осторожно', '[ˈkeə.fəl.i]', 'A1', 'ADVERB'), 
('Correctly', 'Верно;Правильно', '[kəˈrektli]', 'A1', 'ADVERB'), 
('Especially', 'Особенно', '[ɪˈspeʃəli]', 'A1', 'ADVERB'), 
('Friendly', 'Дружелюбно', '[ˈfrendli]', 'A1', 'ADVERB'), 
('Indeed', 'Действительно', '[ɪnˈdiːd]', 'A1', 'ADVERB'), 
('Above', 'Выше', '[əˈbʌv]', 'A1', 'ADVERB'), 
('Accidentally', 'Случайно', '[ˌæk.sɪˈden.təl.i]', 'A1', 'ADVERB'), 
('Actually', 'На самом деле', '[ˈæktʃuəli]', 'A1', 'ADVERB'), 
('Badly', 'Плохо', '[ˈbædli]', 'A1', 'ADVERB'), 
('Besides', 'Помимо этого', '[bɪˈsaɪdz]', 'A1', 'ADVERB'), 
('Briefly', 'Кратко', '[ˈbriːfli]', 'A1', 'ADVERB'), 
('Certainly', 'Конечно', '[ˈsɜːtnli]', 'A1', 'ADVERB'), 
('Daily', 'Ежедневно', '[ˈdeɪli]', 'A1', 'ADVERB'), 
('Dreamily', 'Мечтательно', '[ˈdriː.mɪ.li]', 'A1', 'ADVERB'), 
('Even', 'Даже', '[ˈiːvn]', 'A1', 'ADVERB'), 
('Eventually', 'В конце концов', '[ɪˈventʃuəli]', 'A1', 'ADVERB'), 
('Foolishly', 'Глупо', '[ˈfuːlɪʃli]', 'A1', 'ADVERB'), 
('Forward', 'Вперед', '[ˈfɔːwəd]', 'A1', 'ADVERB'), 
('Ever', 'Когда-либо', '[ˈevə(r)]', 'A1', 'ADVERB'), 
('Equally', 'Одинаково', '[ˈiːkwəli]', 'A1', 'ADVERB'), 
('Fortunately', 'К счастью', '[ˈfɔː.tʃən.ət.li]', 'A1', 'ADVERB'), 
('Honestly', 'Честно', '[ˈɒnɪstli]', 'A1', 'ADVERB'), 
('Instead', 'Вместо', '[ɪnˈsted]', 'A1', 'ADVERB'), 
('Inside', 'Внутри', '[ˌɪnˈsaɪd]', 'A1', 'ADVERB'), 
('Also', 'Также', '[ˈɔːlsəʊ]', 'A1', 'ADVERB'), 
('Hardly', 'С трудом', '[ˈhɑːdli]', 'A1', 'ADVERB'),
('Lately', 'Недавно', '[ˈleɪt.li]', 'A1', 'ADVERB'), 
('Less', 'Меньше', '[les]', 'A1', 'ADVERB'), 
('Loudly', 'Громко;Шумно', '[ˈlaʊd.li]', 'A1', 'ADVERB'), 
('Nearly', 'Около', '[ˈnɪəli]', 'A1', 'ADVERB'), 
('Never', 'Никогда', '[ˈnevə(r)]', 'A1', 'ADVERB'), 
('Only', 'Только', '[ˈəʊnli]', 'A1', 'ADVERB'), 
('Once', 'Один раз', '[wʌns]', 'A1', 'ADVERB'), 
('Often', 'Часто', '[ˈɒfn]', 'A1', 'ADVERB'), 
('Perhaps', 'Возможно', '[pəˈhæps]', 'A1', 'ADVERB'), 
('Quickly', 'Быстро', '[ˈkwɪkli]', 'A1', 'ADVERB'), 
('Probably', 'Вероятно', '[ˈprɒbəbli]', 'A1', 'ADVERB'), 
('Rarely', 'Редко', '[ˈreəli]', 'A1', 'ADVERB'), 
('Really', 'Действительно', '[ˈriːəli]', 'A1', 'ADVERB'), 
('Sometimes', 'Иногда', '[ˈsʌmtaɪmz]', 'A1', 'ADVERB'), 
('Yesterday', 'Вчера', '[ˈjestədeɪ]', 'A1', 'ADVERB'), 
('Thus', 'Таким образом', '[ðʌs]', 'A1', 'ADVERB'), 
('Somehow', 'Как-то', '[ˈsʌmhaʊ]', 'A1', 'ADVERB'), 
('Soon', 'Скоро', '[suːn]', 'A1', 'ADVERB'), 
('Regularly', 'Регулярно', '[ˈreɡjələli]', 'A1', 'ADVERB'), 
('Somewhere', 'Где-то', '[ˈsʌmweə(r)]', 'A1', 'ADVERB');

-- предлоги PREPOSITIONS
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES 
('About', 'О', '[əˈbaʊt]', 'A1', 'PREPOSITION'),
('Above', 'Над', '[əˈbʌv]', 'A1', 'PREPOSITION'),
('Across', 'Через', '[əˈkrɒs]', 'A1', 'PREPOSITION'),
('After', 'После', '[ˈɑːftə(r)]', 'A1', 'PREPOSITION'),
('Against', 'Против', '[əˈɡenst]', 'A1', 'PREPOSITION'),
('Along', 'Вдоль', '[əˈlɒŋ]', 'A1', 'PREPOSITION'),
('Among', 'Среди', '[əˈmʌŋ]', 'A1', 'PREPOSITION'),
('Around', 'Вокруг', '[əˈraʊnd]', 'A1', 'PREPOSITION'),
('At', 'В', '[ət]', 'A1', 'PREPOSITION'),
('Before', 'До', '[bɪˈfɔː(r)]', 'A1', 'PREPOSITION'),
('Behind', 'Позади', '[bɪˈhaɪnd]', 'A1', 'PREPOSITION'),
('Below', 'Ниже', '[bɪˈləʊ]', 'A1', 'PREPOSITION'),
('Beneath', 'Под', '[bɪˈniːθ]', 'A1', 'PREPOSITION'),
('Beside', 'Рядом', '[bɪˈsaɪd]', 'A1', 'PREPOSITION'),
('Between', 'Между', '[bɪˈtwiːn]', 'A1', 'PREPOSITION'),
('Beyond', 'За', '[bɪˈjɒnd]', 'A1', 'PREPOSITION'),
('By', 'У', '[baɪ]', 'A1', 'PREPOSITION'),
('Down', 'Вниз', '[daʊn]', 'A1', 'PREPOSITION'),
('During', 'Во время', '[ˈdjʊərɪŋ]', 'A1', 'PREPOSITION'),
('Except', 'Кроме', '[ɪkˈsept]', 'A1', 'PREPOSITION'),
('For', 'Для', '[fɔː(r)]', 'A1', 'PREPOSITION'),
('From', 'Из', '[frəm]', 'A1', 'PREPOSITION'),
('In', 'В', '[ɪn]', 'A1', 'PREPOSITION'),
('Inside', 'Внутри', '[ˈɪn.saɪd]', 'A1', 'PREPOSITION'),
('Like', 'Как', '[laɪk]', 'A1', 'PREPOSITION'),
('Near', 'Рядом', '[nɪə(r)]', 'A1', 'PREPOSITION'),
('Of', 'Из', '[əv]', 'A1', 'PREPOSITION'),
('Onto', 'На', '[ˈɒntə]', 'A1', 'PREPOSITION'),
('Out', 'Вне', '[aʊt]', 'A1', 'PREPOSITION'),
('Outside', 'Снаружи', '[ˈaʊt.saɪd]', 'A1', 'PREPOSITION'),
('Over', 'Над', '[ˈəʊvə(r)]', 'A1', 'PREPOSITION'),
('Past', 'После', '[pɑːst]', 'A1', 'PREPOSITION'),
('Round', 'Вокруг', '[raʊnd]', 'A1', 'PREPOSITION'),
('Since', 'С (какого-то момента)', '[sɪns]', 'A1', 'PREPOSITION'),
('Through', 'Через', '[θruː]', 'A1', 'PREPOSITION'),
('Throughout', 'На протяжении', '[θruːˈaʊt]', 'A1', 'PREPOSITION'),
('To', 'К', '[tuː]', 'A1', 'PREPOSITION'),
('Under', 'Под', '[ˈʌndə(r)]', 'A1', 'PREPOSITION'),
('Up', 'Вверх', '[ʌp]', 'A1', 'PREPOSITION'),
('Upon', 'На', '[əˈpɒn]', 'A1', 'PREPOSITION'),
('With', 'С (кем-то)', '[wɪð]', 'A1', 'PREPOSITION'),
('Within', 'В пределах', '[wɪˈðɪn]', 'A1', 'PREPOSITION'),
('Without', 'Без', '[wɪˈðaʊt]', 'A1', 'PREPOSITION');


-- CONJUNCTIONS
INSERT INTO words (word, translation, transcription, word_level, word_type)
VALUES 
('And', 'И', '[ænd]', 'A1', 'CONJUNCTION'),
('But', 'Но', '[bʌt]', 'A1', 'CONJUNCTION'),
('Or', 'Или', '[ɔː(r)]', 'A1', 'CONJUNCTION'),
('So', 'Так', '[səʊ]', 'A1', 'CONJUNCTION'),
('Because', 'Потому что', '[bɪˈkɒz]', 'A1', 'CONJUNCTION'),
('If', 'Если', '[ɪf]', 'A1', 'CONJUNCTION'),
('Though', 'Хотя', '[ðəʊ]', 'A1', 'CONJUNCTION'),
('While', 'В то время как', '[waɪl]', 'A1', 'CONJUNCTION'),
('Whether', 'Будь то', '[ˈweðə(r)]', 'A1', 'CONJUNCTION'),
('Until', 'До тех пор пока', '[ənˈtɪl]', 'A1', 'CONJUNCTION'),
('Unless', 'Если не', '[ənˈles]', 'A1', 'CONJUNCTION'),
('After', 'После того как', '[ˈɑːftə(r)]', 'A1', 'CONJUNCTION'),
('Before', 'До того как', '[bɪˈfɔː(r)]', 'A1', 'CONJUNCTION'),
('As', 'Как', '[æz]', 'A1', 'CONJUNCTION'),
('Once', 'Как только', '[wʌns]', 'A1', 'CONJUNCTION'),
('Since', 'С тех пор как', '[sɪns]', 'A1', 'CONJUNCTION'),
('Than', 'Чем', '[ðæn]', 'A1', 'CONJUNCTION'),
('Till', 'До тех пор пока', '[tɪl]', 'A1', 'CONJUNCTION'),
('When', 'Когда', '[wen]', 'A1', 'CONJUNCTION'),
('Where', 'Где', '[weə(r)]', 'A1', 'CONJUNCTION'),
('While', 'В то время как', '[waɪl]', 'A1', 'CONJUNCTION'),
('As if', 'Как будто', '[æz ɪf]', 'A1', 'CONJUNCTION'),
('As soon as', 'Как только', '[æz suːn æz]', 'A1', 'CONJUNCTION'),
('As though', 'Как будто', '[æz ðəʊ]', 'A1', 'CONJUNCTION'),
('Even if', 'Даже если', '[ˈiːvn ɪf]', 'A1', 'CONJUNCTION'),
('Even though', 'Хотя', '[ˈiːvn ðəʊ]', 'A1', 'CONJUNCTION'),
('In case', 'В случае', '[ɪn keɪs]', 'A1', 'CONJUNCTION'),
('Provided that', 'При условии что', '[prəˈvaɪdɪd ðət]', 'A1', 'CONJUNCTION'),
('Unless', 'Если не', '[ənˈles]', 'A1', 'CONJUNCTION'),
('Whenever', 'Всякий раз когда', '[wenˈevə(r)]', 'A1', 'CONJUNCTION'),
('Wherever', 'Где бы ни', '[weərˈevə(r)]', 'A1', 'CONJUNCTION'),
('As if', 'Как будто', '[æz ɪf]', 'A1', 'CONJUNCTION');
